# Generated by Django 5.2.15 on 2026-07-06 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="报废单号"),
                ),
                (
                    "scrap_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="报废日期"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待审核"), (2, "已审核"), (3, "已执行"), (4, "已取消")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总金额"
                    ),
                ),
                ("scrap_reason", models.TextField(verbose_name="报废原因")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_material_scraps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_scraps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="报废人",
                    ),
                ),
                (
                    "material_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_scraps",
                        to="production.materialissue",
                        verbose_name="材料出库单",
                    ),
                ),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_scraps",
                        to="production.productionplan",
                        verbose_name="生产计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "生产报废单",
                "verbose_name_plural": "生产报废单",
                "db_table": "production_material_scrap",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MaterialScrapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                ("material_code", models.CharField(max_length=50, verbose_name="物料编码")),
                (
                    "specification",
                    models.CharField(blank=True, max_length=100, verbose_name="规格型号"),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="单位")),
                (
                    "scrap_quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="报废数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="金额"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "material_issue_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_scrap_items",
                        to="production.materialissueitem",
                        verbose_name="材料出库明细",
                    ),
                ),
                (
                    "material_scrap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.materialscrap",
                        verbose_name="生产报废单",
                    ),
                ),
            ],
            options={
                "verbose_name": "生产报废明细",
                "verbose_name_plural": "生产报废明细",
                "db_table": "production_material_scrap_item",
            },
        ),
    ]
