# Generated by Django 5.2.15 on 2026-06-22 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("department", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="匹配得分(0-100)"
                    ),
                ),
                (
                    "match_level",
                    models.CharField(
                        choices=[
                            ("excellent", "优秀匹配"),
                            ("good", "良好匹配"),
                            ("fair", "一般匹配"),
                            ("poor", "不匹配"),
                        ],
                        max_length=20,
                        verbose_name="匹配等级",
                    ),
                ),
                (
                    "extracted_name",
                    models.CharField(blank=True, max_length=100, verbose_name="提取姓名"),
                ),
                (
                    "extracted_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="提取电话"),
                ),
                (
                    "extracted_email",
                    models.CharField(blank=True, max_length=100, verbose_name="提取邮箱"),
                ),
                (
                    "extracted_education",
                    models.CharField(blank=True, max_length=50, verbose_name="学历"),
                ),
                (
                    "extracted_experience_years",
                    models.IntegerField(blank=True, null=True, verbose_name="工作年限"),
                ),
                ("extracted_skills", models.TextField(blank=True, verbose_name="技能")),
                (
                    "extracted_work_experience",
                    models.TextField(blank=True, verbose_name="工作经历"),
                ),
                ("strength_analysis", models.TextField(verbose_name="优势分析")),
                ("weakness_analysis", models.TextField(verbose_name="不足分析")),
                ("skill_match_detail", models.TextField(verbose_name="技能匹配详情")),
                ("experience_match_detail", models.TextField(verbose_name="经验匹配详情")),
                ("education_match_detail", models.TextField(verbose_name="学历匹配详情")),
                ("comprehensive_evaluation", models.TextField(verbose_name="综合评价")),
                ("recommendation", models.TextField(verbose_name="推荐意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "简历分析报告",
                "verbose_name_plural": "简历分析报告",
                "db_table": "hrbp_resume_analysis_report",
                "ordering": ["-match_score"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="岗位名称")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("full_time", "全职"),
                            ("part_time", "兼职"),
                            ("internship", "实习"),
                            ("contract", "合同工"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="工作类型",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="工作地点")),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="薪资范围（最低）",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="薪资范围（最高）",
                    ),
                ),
                ("headcount", models.IntegerField(default=1, verbose_name="招聘人数")),
                ("description", models.TextField(verbose_name="岗位描述")),
                ("requirements", models.TextField(verbose_name="任职要求")),
                ("responsibilities", models.TextField(verbose_name="岗位职责")),
                ("skills_required", models.TextField(blank=True, verbose_name="技能要求")),
                (
                    "education_required",
                    models.CharField(blank=True, max_length=50, verbose_name="学历要求"),
                ),
                (
                    "experience_years",
                    models.IntegerField(blank=True, null=True, verbose_name="工作年限要求"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位信息",
                "verbose_name_plural": "岗位信息",
                "db_table": "hrbp_job_position",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("sip", "SIP电话"), ("sms", "短信"), ("email", "邮件")],
                        max_length=20,
                        verbose_name="通知方式",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("online", "线上面试"), ("offline", "到公司面试")],
                        max_length=20,
                        verbose_name="面试类型",
                    ),
                ),
                (
                    "interview_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="面试时间"),
                ),
                (
                    "interview_location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="面试地点/在线链接"
                    ),
                ),
                ("message_content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送人",
                    ),
                ),
                (
                    "resume_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_invitations",
                        to="hrbp.resumeanalysisreport",
                        verbose_name="简历报告",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试邀请",
                "verbose_name_plural": "面试邀请",
                "db_table": "hrbp_interview_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(blank=True, max_length=100, verbose_name="候选人姓名"),
                ),
                (
                    "candidate_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
                ),
                (
                    "candidate_email",
                    models.CharField(blank=True, max_length=100, verbose_name="电子邮箱"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("word", "Word文档"), ("image", "图片")],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名称")),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("analyzing", "分析中"),
                            ("completed", "已完成"),
                            ("failed", "分析失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="分析完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_submissions",
                        to="hrbp.jobposition",
                        verbose_name="应聘岗位",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_resumes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历提交",
                "verbose_name_plural": "简历提交",
                "db_table": "hrbp_resume_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="resumeanalysisreport",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_report",
                to="hrbp.resumesubmission",
                verbose_name="简历",
            ),
        ),
    ]
