# Generated by Django 5.2.15 on 2026-06-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrbp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multiple", "多选题"),
                            ("true_false", "判断题"),
                            ("essay", "问答题"),
                            ("code", "编程题"),
                        ],
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='选择题选项列表，格式: [{"key": "A", "text": "选项内容"}]',
                        verbose_name="选项",
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        help_text="正确答案：单选填key，多选填key列表JSON，判断填true/false，问答填参考答案",
                        verbose_name="正确答案",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=6, verbose_name="分值"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "考核题目",
                "verbose_name_plural": "考核题目",
                "db_table": "hrbp_exam_question",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(max_length=50, unique=True, verbose_name="流程阶段"),
                ),
                ("stage_name", models.CharField(max_length=100, verbose_name="阶段名称")),
                (
                    "exec_mode",
                    models.CharField(
                        choices=[
                            ("ai", "AI自动执行"),
                            ("auto", "系统自动执行"),
                            ("manual", "人工手动执行"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="执行模式",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("description", models.TextField(blank=True, verbose_name="阶段说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "招聘流程配置",
                "verbose_name_plural": "招聘流程配置",
                "db_table": "hrbp_recruitment_config",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CandidatePipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("resume_received", "简历已接收"),
                            ("ai_matching", "AI匹配评分"),
                            ("hr_review", "HR审批筛选"),
                            ("contact_interview", "联系面试"),
                            ("interview", "面试中"),
                            ("interview_result", "面试结果评估"),
                            ("online_exam", "在线考核"),
                            ("exam_review", "考核审批"),
                            ("offer", "发放Offer"),
                            ("onboarding", "入职办理"),
                            ("completed", "已完成"),
                            ("rejected", "已淘汰"),
                        ],
                        default="resume_received",
                        max_length=30,
                        verbose_name="当前阶段",
                    ),
                ),
                (
                    "stage_result",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("passed", "通过"),
                            ("rejected", "淘汰"),
                            ("pending_decision", "待决策"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="阶段结果",
                    ),
                ),
                ("hr_comment", models.TextField(blank=True, verbose_name="HR审批意见")),
                (
                    "hr_reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="HR审批时间"),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="综合评分",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "hr_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_pipelines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="HR审批人",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_pipelines",
                        to="hrbp.jobposition",
                        verbose_name="岗位",
                    ),
                ),
                (
                    "resume_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="hrbp.resumesubmission",
                        verbose_name="简历",
                    ),
                ),
            ],
            options={
                "verbose_name": "候选人流程",
                "verbose_name_plural": "候选人流程",
                "db_table": "hrbp_candidate_pipeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "已分配"),
                            ("in_progress", "考核中"),
                            ("submitted", "已提交"),
                            ("ai_graded", "AI已评分"),
                            ("hr_reviewed", "HR已审批"),
                            ("passed", "通过"),
                            ("failed", "未通过"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="提交时间"),
                ),
                (
                    "total_correct",
                    models.IntegerField(blank=True, null=True, verbose_name="正确题数"),
                ),
                (
                    "total_questions",
                    models.IntegerField(blank=True, null=True, verbose_name="总题数"),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="AI评分",
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True, verbose_name="AI评语")),
                (
                    "hr_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="HR调整分",
                    ),
                ),
                ("hr_feedback", models.TextField(blank=True, verbose_name="HR评语")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "exam_link",
                    models.CharField(blank=True, max_length=500, verbose_name="考核链接"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="hrbp.candidatepipeline",
                        verbose_name="候选人流程",
                    ),
                ),
            ],
            options={
                "verbose_name": "候选人考核",
                "verbose_name_plural": "候选人考核",
                "db_table": "hrbp_candidate_exam",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="考生答案")),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否自动判对"),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="AI给分",
                    ),
                ),
                ("ai_comment", models.TextField(blank=True, verbose_name="AI点评")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作答时间"),
                ),
                (
                    "candidate_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="hrbp.candidateexam",
                        verbose_name="考核记录",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_answers",
                        to="hrbp.examquestion",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题记录",
                "verbose_name_plural": "答题记录",
                "db_table": "hrbp_exam_answer",
            },
        ),
        migrations.CreateModel(
            name="OnboardingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待入职"),
                            ("in_progress", "办理中"),
                            ("completed", "已入职"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="预计入职日期"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际入职日期"),
                ),
                (
                    "offer_letter",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Offer文件路径"
                    ),
                ),
                (
                    "salary_offered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Offer薪资",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_onboardings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
                (
                    "pipeline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="hrbp.candidatepipeline",
                        verbose_name="候选人流程",
                    ),
                ),
            ],
            options={
                "verbose_name": "入职记录",
                "verbose_name_plural": "入职记录",
                "db_table": "hrbp_onboarding_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="考核名称")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("technical", "技术考核"),
                            ("personality", "性格测试"),
                            ("comprehensive", "综合能力"),
                            ("professional", "专业知识"),
                            ("custom", "自定义"),
                        ],
                        default="technical",
                        max_length=20,
                        verbose_name="考核类型",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                        default="medium",
                        max_length=10,
                        verbose_name="难度",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="考核说明")),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="考试时长(分钟)"),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2, default=60.0, max_digits=5, verbose_name="及格分"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, default=100.0, max_digits=5, verbose_name="总分"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "在线考核",
                "verbose_name_plural": "在线考核",
                "db_table": "hrbp_online_exam",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="hrbp.onlineexam",
                verbose_name="所属考核",
            ),
        ),
        migrations.AddField(
            model_name="candidateexam",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_exams",
                to="hrbp.onlineexam",
                verbose_name="考核",
            ),
        ),
        migrations.CreateModel(
            name="PipelineStageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=30, verbose_name="阶段")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("enter", "进入阶段"),
                            ("ai_process", "AI处理"),
                            ("auto_process", "自动处理"),
                            ("manual_approve", "人工通过"),
                            ("manual_reject", "人工淘汰"),
                            ("auto_advance", "自动推进"),
                            ("notification_sent", "已发送通知"),
                            ("notification_failed", "通知失败"),
                            ("exit", "离开阶段"),
                        ],
                        max_length=30,
                        verbose_name="操作",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="详情")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_logs",
                        to="hrbp.candidatepipeline",
                        verbose_name="流程",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程操作日志",
                "verbose_name_plural": "流程操作日志",
                "db_table": "hrbp_pipeline_stage_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_type",
                    models.CharField(
                        choices=[("sms", "短信"), ("email", "邮件"), ("phone", "电话")],
                        max_length=10,
                        verbose_name="通知方式",
                    ),
                ),
                (
                    "scene",
                    models.CharField(
                        choices=[
                            ("interview_invite", "面试邀请"),
                            ("exam_invite", "考核邀请"),
                            ("offer_notice", "Offer通知"),
                            ("onboarding_notice", "入职通知"),
                            ("rejection_notice", "淘汰通知"),
                            ("custom", "自定义"),
                        ],
                        max_length=30,
                        verbose_name="通知场景",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="接收人")),
                ("contact_info", models.CharField(max_length=200, verbose_name="联系方式")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="标题"),
                ),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("delivered", "已送达"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=200, verbose_name="外部服务ID"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hrbp.candidatepipeline",
                        verbose_name="候选人流程",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_recruitment_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送人",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘通知",
                "verbose_name_plural": "招聘通知",
                "db_table": "hrbp_recruitment_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="candidatepipeline",
            index=models.Index(
                fields=["current_stage"], name="hrbp_candid_current_5fb05b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatepipeline",
            index=models.Index(
                fields=["is_active", "current_stage"],
                name="hrbp_candid_is_acti_cbe974_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidateexamanswer",
            unique_together={("candidate_exam", "question")},
        ),
    ]
