# Generated by Django 5.2.1 on 2026-06-29 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrbp", "0002_add_recruitment_pipeline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='标签列表，如 ["Python", "Django", "中级"]',
                verbose_name="标签",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBankGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="分组名称")),
                (
                    "function_tags",
                    models.JSONField(
                        blank=True, default=list, help_text="职能标签", verbose_name="职能标签"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                        default="medium",
                        max_length=10,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="通用标签", verbose_name="标签"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分组说明")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_question_bank_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_bank_groups",
                        to="hrbp.jobposition",
                        verbose_name="关联岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "题库分组",
                "verbose_name_plural": "题库分组",
                "db_table": "hrbp_question_bank_group",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAutoGenerationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则说明")),
                (
                    "total_questions",
                    models.IntegerField(default=20, verbose_name="题目总数"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, default=100.0, max_digits=6, verbose_name="总分"
                    ),
                ),
                (
                    "difficulty_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="难度分布百分比",
                        verbose_name="难度分布",
                    ),
                ),
                (
                    "question_type_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="题型数量分布",
                        verbose_name="题型分布",
                    ),
                ),
                (
                    "tag_requirements",
                    models.JSONField(
                        blank=True, default=dict, help_text="标签要求", verbose_name="标签要求"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("active", "启用"), ("archived", "归档")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exam_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "position_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_generation_rules",
                        to="hrbp.jobposition",
                        verbose_name="岗位筛选",
                    ),
                ),
                (
                    "bank_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="generation_rules",
                        to="hrbp.questionbankgroup",
                        verbose_name="题库分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动组卷规则",
                "verbose_name_plural": "自动组卷规则",
                "db_table": "hrbp_exam_auto_generation_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="bank_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="hrbp.questionbankgroup",
                verbose_name="所属题库分组",
            ),
        ),
    ]
