# Generated by Django 5.2.5 on 2026-01-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='企业名称')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='法定代表人')),
                ('registered_capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='注册资本')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('registration_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='登记状态')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='注册地址')),
                ('tianyancha_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='天眼查链接')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
    ]
