# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(default=0, verbose_name='报销企业主体')),
                ('code', models.CharField(default='', max_length=100, verbose_name='报销编码')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='报销总金额')),
                ('income_month', models.IntegerField(default=0, verbose_name='入账月份')),
                ('expense_time', models.BigIntegerField(default=0, verbose_name='原始单据日期')),
                ('admin_id', models.PositiveIntegerField(default=0, verbose_name='报销人ID')),
                ('did', models.IntegerField(default=0, verbose_name='报销部门ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='关联项目ID')),
                ('file_ids', models.CharField(default='', max_length=500, verbose_name='附件ID')),
                ('pay_status', models.SmallIntegerField(default=0, verbose_name='打款状态：0待打款,1已打款')),
                ('pay_admin_id', models.IntegerField(default=0, verbose_name='打款人ID')),
                ('pay_time', models.BigIntegerField(default=0, verbose_name='最后打款时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('check_status', models.SmallIntegerField(default=0, verbose_name='审核状态:0待审核,1审核中,2审核通过,3审核不通过,4撤销审核')),
                ('check_flow_id', models.IntegerField(default=0, verbose_name='审核流程id')),
                ('check_step_sort', models.IntegerField(default=0, verbose_name='当前审批步骤')),
                ('check_uids', models.CharField(default='', max_length=500, verbose_name='当前审批人ID')),
                ('check_last_uid', models.CharField(default='', max_length=500, verbose_name='上一审批人ID')),
                ('check_history_uids', models.CharField(default='', max_length=500, verbose_name='历史审批人ID')),
                ('check_copy_uids', models.CharField(default='', max_length=500, verbose_name='抄送人ID')),
                ('check_time', models.BigIntegerField(default=0, verbose_name='审核通过时间')),
                ('create_time', models.PositiveBigIntegerField(default=0, verbose_name='创建时间')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='是否自动生成')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='到账金额')),
                ('income_date', models.DateTimeField(verbose_name='到账日期')),
                ('file_ids', models.CharField(default='', max_length=500, verbose_name='附件ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.PositiveBigIntegerField(default=0, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回款记录',
                'verbose_name_plural': '回款记录',
                'db_table': 'finance_income',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(default=0, verbose_name='申请部门ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='开票金额')),
                ('invoice_type', models.SmallIntegerField(default=2, verbose_name='发票类型：1增值税专用发票,2普通发票')),
                ('invoice_title', models.CharField(max_length=200, verbose_name='开票抬头')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='纳税人识别号')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('invoiced', '已开票')], default='pending', max_length=20, verbose_name='申请状态')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('invoice_time', models.DateTimeField(blank=True, null=True, verbose_name='开票时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '开票申请',
                'verbose_name_plural': '开票申请',
                'db_table': 'finance_invoice_request',
            },
        ),
        migrations.CreateModel(
            name='OrderFinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='订单总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额')),
                ('payment_status', models.CharField(choices=[('pending', '待付款'), ('partial', '部分付款'), ('paid', '已付款'), ('overdue', '逾期')], default='pending', max_length=20, verbose_name='付款状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='付款到期日')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单财务记录',
                'verbose_name_plural': '订单财务记录',
                'db_table': 'finance_order_record',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='打款金额')),
                ('payment_date', models.DateTimeField(verbose_name='打款日期')),
                ('file_ids', models.CharField(default='', max_length=500, verbose_name='附件ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.PositiveBigIntegerField(default=0, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '打款记录',
                'verbose_name_plural': '打款记录',
                'db_table': 'finance_payment',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100, verbose_name='发票号码')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='发票金额')),
                ('did', models.IntegerField(default=0, verbose_name='发票申请部门')),
                ('admin_id', models.PositiveIntegerField(default=0, verbose_name='发票申请人ID')),
                ('open_status', models.SmallIntegerField(default=0, verbose_name='开票状态：0未开票 1已开票 2已作废')),
                ('open_admin_id', models.IntegerField(default=0, verbose_name='发票开具人')),
                ('open_time', models.BigIntegerField(default=0, verbose_name='发票开具时间')),
                ('delivery', models.CharField(default='', max_length=100, verbose_name='快递单号')),
                ('types', models.SmallIntegerField(default=0, verbose_name='抬头类型：1企业2个人')),
                ('invoice_type', models.SmallIntegerField(default=0, verbose_name='发票类型：1增值税专用发票,2普通发票,3专用发票')),
                ('invoice_subject', models.IntegerField(default=0, verbose_name='关联发票主体ID')),
                ('invoice_title', models.CharField(default='', max_length=100, verbose_name='开票抬头')),
                ('invoice_tax', models.CharField(default='', max_length=100, verbose_name='纳税人识别号')),
                ('invoice_phone', models.CharField(default='', max_length=100, verbose_name='电话号码')),
                ('invoice_address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('invoice_bank', models.CharField(default='', max_length=100, verbose_name='开户银行')),
                ('invoice_account', models.CharField(default='', max_length=100, verbose_name='银行账号')),
                ('invoice_banking', models.CharField(default='', max_length=100, verbose_name='银行营业网点')),
                ('file_ids', models.CharField(default='', max_length=500, verbose_name='附件ID')),
                ('other_file_ids', models.CharField(default='', max_length=500, verbose_name='其他附件ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('enter_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='已到账金额')),
                ('enter_status', models.SmallIntegerField(default=0, verbose_name='回款状态：0未回款 1部分回款 2全部回款')),
                ('enter_time', models.BigIntegerField(default=0, verbose_name='最新回款时间')),
                ('check_status', models.SmallIntegerField(default=0, verbose_name='审核状态:0待审核,1审核中,2审核通过,3审核不通过,4撤销审核')),
                ('check_flow_id', models.IntegerField(default=0, verbose_name='审核流程id')),
                ('check_step_sort', models.IntegerField(default=0, verbose_name='当前审批步骤')),
                ('check_uids', models.CharField(default='', max_length=500, verbose_name='当前审批人ID')),
                ('check_last_uid', models.CharField(default='', max_length=500, verbose_name='上一审批人ID')),
                ('check_history_uids', models.CharField(default='', max_length=500, verbose_name='历史审批人ID')),
                ('check_copy_uids', models.CharField(default='', max_length=500, verbose_name='抄送人ID')),
                ('check_time', models.BigIntegerField(default=0, verbose_name='审核通过时间')),
                ('create_time', models.PositiveBigIntegerField(default=0, verbose_name='创建时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to='customer.customercontract', verbose_name='关联合同')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_invoices', to='customer.customer', verbose_name='关联客户')),
            ],
        ),
    ]
