# Generated by Django 4.2.27 on 2026-03-04 13:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(default="", max_length=100, verbose_name="报销编码"),
                ),
                ("subject_id", models.IntegerField(default=0, verbose_name="报销企业主体")),
                (
                    "admin_id",
                    models.PositiveIntegerField(default=0, verbose_name="报销人ID"),
                ),
                ("did", models.IntegerField(default=0, verbose_name="报销部门ID")),
                ("project_id", models.IntegerField(default=0, verbose_name="关联项目ID")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="报销总金额"
                    ),
                ),
                ("income_month", models.IntegerField(default=0, verbose_name="入账月份")),
                (
                    "expense_time",
                    models.BigIntegerField(default=0, verbose_name="原始单据日期"),
                ),
                (
                    "file_ids",
                    models.CharField(default="", max_length=500, verbose_name="附件ID"),
                ),
                (
                    "pay_status",
                    models.SmallIntegerField(default=0, verbose_name="打款状态：0待打款,1已打款"),
                ),
                ("pay_admin_id", models.IntegerField(default=0, verbose_name="打款人ID")),
                ("pay_time", models.BigIntegerField(default=0, verbose_name="最后打款时间")),
                (
                    "check_status",
                    models.SmallIntegerField(
                        default=0, verbose_name="审核状态:0待审核,1审核中,2审核通过,3审核不通过,4撤销审核"
                    ),
                ),
                (
                    "check_flow_id",
                    models.IntegerField(default=0, verbose_name="审核流程id"),
                ),
                (
                    "check_step_sort",
                    models.IntegerField(default=0, verbose_name="当前审批步骤"),
                ),
                (
                    "check_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="当前审批人ID"
                    ),
                ),
                (
                    "check_last_uid",
                    models.CharField(
                        default="", max_length=500, verbose_name="上一审批人ID"
                    ),
                ),
                (
                    "check_history_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="历史审批人ID"
                    ),
                ),
                (
                    "check_copy_uids",
                    models.CharField(default="", max_length=500, verbose_name="抄送人ID"),
                ),
                (
                    "check_time",
                    models.BigIntegerField(default=0, verbose_name="审核通过时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "报销申请",
                "verbose_name_plural": "报销申请",
                "db_table": "finance_expense",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_id",
                    models.BigIntegerField(default=0, verbose_name="关联发票ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="到账金额"
                    ),
                ),
                ("income_date", models.DateTimeField(verbose_name="到账日期")),
                (
                    "file_ids",
                    models.CharField(default="", max_length=500, verbose_name="附件ID"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "回款记录",
                "verbose_name_plural": "回款记录",
                "db_table": "finance_income",
                "ordering": ["-income_date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(default="", max_length=100, verbose_name="发票号码"),
                ),
                ("customer_id", models.IntegerField(default=0, verbose_name="关联客户ID")),
                (
                    "contract_id",
                    models.BigIntegerField(default=0, verbose_name="关联合同ID"),
                ),
                (
                    "project_id",
                    models.BigIntegerField(default=0, verbose_name="关联项目ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="发票金额"
                    ),
                ),
                ("did", models.IntegerField(default=0, verbose_name="发票申请部门")),
                (
                    "admin_id",
                    models.PositiveIntegerField(default=0, verbose_name="发票申请人ID"),
                ),
                (
                    "open_status",
                    models.SmallIntegerField(
                        default=0, verbose_name="开票状态：0未开票 1已开票 2已作废"
                    ),
                ),
                ("open_admin_id", models.IntegerField(default=0, verbose_name="发票开具人")),
                ("open_time", models.BigIntegerField(default=0, verbose_name="发票开具时间")),
                (
                    "delivery",
                    models.CharField(default="", max_length=100, verbose_name="快递单号"),
                ),
                (
                    "types",
                    models.SmallIntegerField(default=0, verbose_name="抬头类型：1企业2个人"),
                ),
                (
                    "invoice_type",
                    models.SmallIntegerField(default=0, verbose_name="发票类型"),
                ),
                (
                    "invoice_subject",
                    models.IntegerField(default=0, verbose_name="关联发票主体ID"),
                ),
                (
                    "invoice_title",
                    models.CharField(default="", max_length=100, verbose_name="开票抬头"),
                ),
                (
                    "invoice_tax",
                    models.CharField(default="", max_length=100, verbose_name="纳税人识别号"),
                ),
                (
                    "invoice_phone",
                    models.CharField(default="", max_length=100, verbose_name="电话号码"),
                ),
                (
                    "invoice_address",
                    models.CharField(default="", max_length=100, verbose_name="地址"),
                ),
                (
                    "invoice_bank",
                    models.CharField(default="", max_length=100, verbose_name="开户银行"),
                ),
                (
                    "invoice_account",
                    models.CharField(default="", max_length=100, verbose_name="银行账号"),
                ),
                (
                    "invoice_banking",
                    models.CharField(default="", max_length=100, verbose_name="银行营业网点"),
                ),
                (
                    "file_ids",
                    models.CharField(default="", max_length=500, verbose_name="附件ID"),
                ),
                (
                    "other_file_ids",
                    models.CharField(default="", max_length=500, verbose_name="其他附件ID"),
                ),
                (
                    "enter_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="已到账金额",
                    ),
                ),
                (
                    "enter_status",
                    models.SmallIntegerField(
                        default=0, verbose_name="回款状态：0未回款 1部分回款 2全部回款"
                    ),
                ),
                (
                    "enter_time",
                    models.BigIntegerField(default=0, verbose_name="最新回款时间"),
                ),
                (
                    "check_status",
                    models.SmallIntegerField(default=0, verbose_name="审核状态"),
                ),
                (
                    "check_flow_id",
                    models.IntegerField(default=0, verbose_name="审核流程id"),
                ),
                (
                    "check_step_sort",
                    models.IntegerField(default=0, verbose_name="当前审批步骤"),
                ),
                (
                    "check_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="当前审批人ID"
                    ),
                ),
                (
                    "check_last_uid",
                    models.CharField(
                        default="", max_length=500, verbose_name="上一审批人ID"
                    ),
                ),
                (
                    "check_history_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="历史审批人ID"
                    ),
                ),
                (
                    "check_copy_uids",
                    models.CharField(default="", max_length=500, verbose_name="抄送人ID"),
                ),
                (
                    "check_time",
                    models.BigIntegerField(default=0, verbose_name="审核通过时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "发票",
                "verbose_name_plural": "发票",
                "db_table": "finance_invoice",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(default=0, verbose_name="关联订单ID")),
                ("applicant_id", models.IntegerField(default=0, verbose_name="申请人ID")),
                (
                    "department_id",
                    models.IntegerField(default=0, verbose_name="申请部门ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="开票金额"
                    ),
                ),
                (
                    "invoice_type",
                    models.SmallIntegerField(default=2, verbose_name="发票类型"),
                ),
                (
                    "invoice_title",
                    models.CharField(max_length=200, verbose_name="开票抬头"),
                ),
                (
                    "tax_number",
                    models.CharField(blank=True, max_length=100, verbose_name="纳税人识别号"),
                ),
                ("reason", models.TextField(verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("invoiced", "已开票"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="申请状态",
                    ),
                ),
                ("reviewer_id", models.IntegerField(default=0, verbose_name="审核人ID")),
                ("review_time", models.BigIntegerField(default=0, verbose_name="审核时间")),
                ("review_comment", models.TextField(blank=True, verbose_name="审核意见")),
                ("invoice_id", models.IntegerField(default=0, verbose_name="关联发票ID")),
                (
                    "invoice_time",
                    models.BigIntegerField(default=0, verbose_name="开票时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "开票申请",
                "verbose_name_plural": "开票申请",
                "db_table": "finance_invoice_request",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OrderFinanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(default=0, verbose_name="关联订单ID")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="订单总金额"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="已付金额",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款"),
                            ("partial", "部分付款"),
                            ("paid", "已付款"),
                            ("overdue", "逾期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="付款状态",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="付款到期日"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "订单财务记录",
                "verbose_name_plural": "订单财务记录",
                "db_table": "finance_order_record",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_id",
                    models.BigIntegerField(default=0, verbose_name="关联报销ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="打款金额"
                    ),
                ),
                ("payment_date", models.DateTimeField(verbose_name="打款日期")),
                (
                    "file_ids",
                    models.CharField(default="", max_length=500, verbose_name="附件ID"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "付款记录",
                "verbose_name_plural": "付款记录",
                "db_table": "finance_payment",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceVerifyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_id",
                    models.BigIntegerField(default=0, verbose_name="关联发票ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="核销金额"
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verify_records",
                        to="finance.income",
                        verbose_name="关联回款",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票核销记录",
                "verbose_name_plural": "发票核销记录",
                "db_table": "finance_invoice_verify_record",
                "ordering": ["-id"],
            },
        ),
    ]
