# Generated by Django 5.2.1 on 2026-06-05 17:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="", max_length=100, verbose_name="应付编号"
                    ),
                ),
                (
                    "supplier_id",
                    models.IntegerField(default=0, verbose_name="供应商ID"),
                ),
                (
                    "expense_id",
                    models.BigIntegerField(default=0, verbose_name="报销ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="应付金额"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="已付金额",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款"),
                            ("partial", "部分付款"),
                            ("settled", "已结清"),
                            ("overdue", "已逾期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "应付账款",
                "verbose_name_plural": "应付账款",
                "db_table": "finance_accounts_payable",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="AccountsReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="", max_length=100, verbose_name="应收编号"
                    ),
                ),
                ("customer_id", models.IntegerField(default=0, verbose_name="客户ID")),
                ("order_id", models.IntegerField(default=0, verbose_name="订单ID")),
                (
                    "invoice_id",
                    models.BigIntegerField(default=0, verbose_name="发票ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="应收金额"
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="已收金额",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待收款"),
                            ("partial", "部分收款"),
                            ("settled", "已结清"),
                            ("overdue", "已逾期"),
                            ("bad_debt", "坏账"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "应收账款",
                "verbose_name_plural": "应收账款",
                "db_table": "finance_accounts_receivable",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="FinanceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="账户名称")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("bank", "银行账户"),
                            ("cash", "现金账户"),
                            ("third_party", "第三方支付账户"),
                            ("other", "其他账户"),
                        ],
                        default="bank",
                        max_length=20,
                        verbose_name="账户类型",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="开户银行"
                    ),
                ),
                (
                    "account_no",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="账号"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="期初余额",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="当前余额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "资金账户",
                "verbose_name_plural": "资金账户",
                "db_table": "finance_account",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="FinanceBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="预算名称")),
                (
                    "department_id",
                    models.IntegerField(default=0, verbose_name="部门ID"),
                ),
                ("project_id", models.IntegerField(default=0, verbose_name="项目ID")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("month", "月度"),
                            ("quarter", "季度"),
                            ("year", "年度"),
                        ],
                        default="month",
                        max_length=20,
                        verbose_name="预算周期",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "budget_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="预算金额"
                    ),
                ),
                (
                    "used_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="已用金额",
                    ),
                ),
                (
                    "warning_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80"),
                        max_digits=5,
                        verbose_name="预警比例",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "执行中"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "预算管理",
                "verbose_name_plural": "预算管理",
                "db_table": "finance_budget",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="LedgerVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_no",
                    models.CharField(default="", max_length=100, verbose_name="凭证号"),
                ),
                ("voucher_date", models.DateField(verbose_name="凭证日期")),
                ("summary", models.CharField(max_length=200, verbose_name="摘要")),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="借方金额",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="贷方金额",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="来源类型"
                    ),
                ),
                ("source_id", models.BigIntegerField(default=0, verbose_name="来源ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("posted", "已过账"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("posted_by", models.IntegerField(default=0, verbose_name="过账人ID")),
                (
                    "posted_time",
                    models.BigIntegerField(default=0, verbose_name="过账时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "总账凭证",
                "verbose_name_plural": "总账凭证",
                "db_table": "finance_ledger_voucher",
                "ordering": ["-voucher_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateTimeField(verbose_name="交易时间")),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "收入"), ("out", "支出")],
                        max_length=10,
                        verbose_name="收支方向",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="交易金额"
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="交易对方"
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="交易流水号",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="用途"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[("unmatched", "未匹配"), ("matched", "已匹配")],
                        default="unmatched",
                        max_length=20,
                        verbose_name="匹配状态",
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="关联业务类型",
                    ),
                ),
                (
                    "related_id",
                    models.BigIntegerField(default=0, verbose_name="关联业务ID"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.financeaccount",
                        verbose_name="资金账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "银行流水",
                "verbose_name_plural": "银行流水",
                "db_table": "finance_bank_transaction",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="对账期间")),
                (
                    "book_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="账面余额",
                    ),
                ),
                (
                    "bank_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="银行余额",
                    ),
                ),
                (
                    "difference_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="差异金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待对账"),
                            ("balanced", "已平衡"),
                            ("difference", "有差异"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reconciled_by",
                    models.IntegerField(default=0, verbose_name="对账人ID"),
                ),
                (
                    "reconciled_time",
                    models.BigIntegerField(default=0, verbose_name="对账时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="finance.financeaccount",
                        verbose_name="资金账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "银行对账",
                "verbose_name_plural": "银行对账",
                "db_table": "finance_bank_reconciliation",
                "ordering": ["-create_time"],
                "unique_together": {("account", "period")},
            },
        ),
    ]
