# Generated by Django 5.2.1 on 2026-06-05 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_accountspayable_accountsreceivable_financeaccount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_no",
                    models.CharField(
                        default="", max_length=100, verbose_name="分摊编号"
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="分摊期间")),
                (
                    "source_type",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="来源类型"
                    ),
                ),
                ("source_id", models.BigIntegerField(default=0, verbose_name="来源ID")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="分摊总额"
                    ),
                ),
                (
                    "department_id",
                    models.IntegerField(default=0, verbose_name="部门ID"),
                ),
                ("project_id", models.IntegerField(default=0, verbose_name="项目ID")),
                (
                    "allocation_basis",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="分摊依据"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("allocated", "已分摊"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "成本分摊",
                "verbose_name_plural": "成本分摊",
                "db_table": "finance_cost_allocation",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriodClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="会计期间"
                    ),
                ),
                (
                    "income_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="收入金额",
                    ),
                ),
                (
                    "expense_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="费用金额",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="利润金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未结账"),
                            ("closing", "结账中"),
                            ("closed", "已结账"),
                            ("reopened", "已反结账"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("closed_by", models.IntegerField(default=0, verbose_name="结账人ID")),
                (
                    "closed_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="结账时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "期间结账",
                "verbose_name_plural": "期间结账",
                "db_table": "finance_period_close",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        default="", max_length=100, verbose_name="报表编号"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "资产负债表"),
                            ("income_statement", "利润表"),
                            ("cash_flow", "现金流量表"),
                            ("management", "经营分析报表"),
                        ],
                        max_length=30,
                        verbose_name="报表类型",
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="报表期间")),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="资产总额",
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="负债总额",
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="权益总额",
                    ),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="收入金额",
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="成本费用",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="利润金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("generated", "已生成"),
                            ("approved", "已确认"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "generated_by",
                    models.IntegerField(default=0, verbose_name="生成人ID"),
                ),
                (
                    "generated_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="生成时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "财务报表",
                "verbose_name_plural": "财务报表",
                "db_table": "finance_report",
                "ordering": ["-period", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(max_length=100, verbose_name="资产编号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="资产名称")),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="资产类别"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="购置日期")),
                (
                    "original_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="原值"
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="残值",
                    ),
                ),
                (
                    "depreciation_months",
                    models.PositiveIntegerField(default=36, verbose_name="折旧月数"),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="累计折旧",
                    ),
                ),
                (
                    "department_id",
                    models.IntegerField(default=0, verbose_name="使用部门ID"),
                ),
                (
                    "responsible_user_id",
                    models.IntegerField(default=0, verbose_name="负责人ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "使用中"),
                            ("idle", "闲置"),
                            ("disposed", "已处置"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "固定资产",
                "verbose_name_plural": "固定资产",
                "db_table": "finance_fixed_asset",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TaxRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="税务期间")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "增值税"),
                            ("income_tax", "企业所得税"),
                            ("surtax", "附加税"),
                            ("stamp", "印花税"),
                            ("other", "其他税费"),
                        ],
                        max_length=30,
                        verbose_name="税种",
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="计税金额",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="税率",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="税额",
                    ),
                ),
                (
                    "declared_date",
                    models.DateField(blank=True, null=True, verbose_name="申报日期"),
                ),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="缴纳日期"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待申报"),
                            ("declared", "已申报"),
                            ("paid", "已缴纳"),
                            ("overdue", "已逾期"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "税务管理",
                "verbose_name_plural": "税务管理",
                "db_table": "finance_tax_record",
                "ordering": ["-create_time"],
            },
        ),
    ]
