# Generated by Django 5.2.1 on 2026-06-06 10:19

import django.db.models.deletion
from django.db import migrations, models


def link_existing_assets(apps, schema_editor):
    FixedAsset = apps.get_model("finance", "FixedAsset")
    Asset = apps.get_model("system", "Asset")
    used_asset_ids = set()

    for finance_asset in FixedAsset.objects.all().order_by("id"):
        asset_code = getattr(finance_asset, "asset_code", "") or ""
        asset_name = getattr(finance_asset, "name", "") or ""
        asset = None
        if asset_code:
            asset = Asset.objects.filter(asset_number=asset_code).first()
        if not asset and asset_name:
            asset = Asset.objects.filter(name=asset_name).order_by("id").first()
        if asset and asset.id not in used_asset_ids:
            finance_asset.asset_id = asset.id
            finance_asset.save(update_fields=["asset"])
            used_asset_ids.add(asset.id)


def unlink_existing_assets(apps, schema_editor):
    FixedAsset = apps.get_model("finance", "FixedAsset")
    FixedAsset.objects.update(asset=None)


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_costallocation_financialperiodclose_financialreport_and_more",
        ),
        ("system", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixedasset",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "固定资产财务档案",
                "verbose_name_plural": "固定资产财务档案",
            },
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_profile",
                to="system.asset",
                verbose_name="行政固定资产",
            ),
        ),
        migrations.RunPython(link_existing_assets, unlink_existing_assets),
        migrations.RemoveField(
            model_name="fixedasset",
            name="asset_code",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="category",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="department_id",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="name",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="original_value",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="responsible_user_id",
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "计提中"),
                    ("paused", "暂停计提"),
                    ("disposed", "已处置"),
                ],
                default="active",
                max_length=20,
                verbose_name="财务状态",
            ),
        ),
    ]
