# Generated by Django 5.2.1 on 2026-06-06 11:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_fixedasset_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="指标期间")),
                (
                    "ratio_type",
                    models.CharField(
                        choices=[
                            ("profitability", "盈利能力"),
                            ("solvency", "偿债能力"),
                            ("operation", "营运能力"),
                            ("growth", "成长能力"),
                            ("cash", "现金能力"),
                        ],
                        max_length=30,
                        verbose_name="指标类型",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="指标名称")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="指标值",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="目标值",
                    ),
                ),
                (
                    "warning_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="预警值",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="%", max_length=20, verbose_name="单位"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("warning", "预警"),
                            ("risk", "风险"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "财务指标",
                "verbose_name_plural": "财务指标",
                "db_table": "finance_financial_ratio",
                "ordering": ["-period", "ratio_type"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_no",
                    models.CharField(
                        default="", max_length=100, verbose_name="计划编号"
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("in", "流入"), ("out", "流出")],
                        max_length=10,
                        verbose_name="流向",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="类别"
                    ),
                ),
                ("expected_date", models.DateField(verbose_name="预计日期")),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="预计金额"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="实际金额",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="来源类型"
                    ),
                ),
                ("source_id", models.BigIntegerField(default=0, verbose_name="来源ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "计划中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_flow_plans",
                        to="finance.financeaccount",
                        verbose_name="资金账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "现金流计划",
                "verbose_name_plural": "现金流计划",
                "db_table": "finance_cash_flow_plan",
                "ordering": ["expected_date", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="科目编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="科目名称")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "资产"),
                            ("liability", "负债"),
                            ("equity", "权益"),
                            ("income", "收入"),
                            ("cost", "成本"),
                            ("expense", "费用"),
                        ],
                        max_length=20,
                        verbose_name="科目类型",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="科目级次"
                    ),
                ),
                ("is_leaf", models.BooleanField(default=True, verbose_name="是否末级")),
                (
                    "balance_direction",
                    models.CharField(
                        choices=[("debit", "借方"), ("credit", "贷方")],
                        default="debit",
                        max_length=10,
                        verbose_name="余额方向",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.chartofaccount",
                        verbose_name="上级科目",
                    ),
                ),
            ],
            options={
                "verbose_name": "会计科目",
                "verbose_name_plural": "会计科目",
                "db_table": "finance_chart_of_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accrual_no",
                    models.CharField(
                        default="", max_length=100, verbose_name="计提编号"
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="计提期间")),
                (
                    "expense_type",
                    models.CharField(max_length=100, verbose_name="费用类型"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="计提金额"
                    ),
                ),
                (
                    "department_id",
                    models.IntegerField(default=0, verbose_name="部门ID"),
                ),
                ("project_id", models.IntegerField(default=0, verbose_name="项目ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("accrued", "已计提"),
                            ("reversed", "已冲销"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("accrued_by", models.IntegerField(default=0, verbose_name="计提人ID")),
                (
                    "accrued_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="计提时间"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_accruals",
                        to="finance.ledgervoucher",
                        verbose_name="关联凭证",
                    ),
                ),
            ],
            options={
                "verbose_name": "费用计提",
                "verbose_name_plural": "费用计提",
                "db_table": "finance_expense_accrual",
                "ordering": ["-period", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="LedgerVoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="摘要"
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="借方金额",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="贷方金额",
                    ),
                ),
                (
                    "auxiliary_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="辅助核算类型",
                    ),
                ),
                (
                    "auxiliary_id",
                    models.BigIntegerField(default=0, verbose_name="辅助核算ID"),
                ),
                (
                    "create_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="创建时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_lines",
                        to="finance.chartofaccount",
                        verbose_name="会计科目",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.ledgervoucher",
                        verbose_name="总账凭证",
                    ),
                ),
            ],
            options={
                "verbose_name": "凭证明细",
                "verbose_name_plural": "凭证明细",
                "db_table": "finance_ledger_voucher_line",
                "ordering": ["voucher_id", "id"],
            },
        ),
    ]
