# Generated by Django 5.2.15 on 2026-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_financialratio_cashflowplan_chartofaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_id",
            field=models.BigIntegerField(default=0, verbose_name="关联客户ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.BigIntegerField(default=0, verbose_name="关联订单ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="project_id",
            field=models.BigIntegerField(default=0, verbose_name="关联项目ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="purchase_contract_id",
            field=models.BigIntegerField(default=0, verbose_name="关联采购合同ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="purchase_order_id",
            field=models.BigIntegerField(default=0, verbose_name="关联采购订单ID"),
        ),
    ]
