# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="资产编号"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="资产名称")),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="型号"),
                ),
                ("specification", models.TextField(
                    blank=True, verbose_name="规格参数")),
                ("purchase_date", models.DateField(verbose_name="购买日期")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="购买价格"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="供应商"),
                ),
                (
                    "warranty_period",
                    models.IntegerField(default=12, verbose_name="保修期(月)"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="存放位置"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("repair", "维修中"),
                            ("scrap", "报废"),
                            ("lost", "丢失"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="备注说明")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "固定资产",
                "verbose_name_plural": "固定资产",
                "db_table": "system_asset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品牌名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="品牌代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="品牌描述")),
                (
                    "logo",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="品牌Logo"),
                ),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "品牌管理",
                "verbose_name_plural": "品牌管理",
                "db_table": "system_asset_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "资产分类",
                "verbose_name_plural": "资产分类",
                "db_table": "system_asset_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssetRepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fault_description", models.TextField(verbose_name="故障描述")),
                (
                    "repair_description",
                    models.TextField(blank=True, verbose_name="维修说明"),
                ),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="维修费用",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "report_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="报修时间"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始维修时间"),
                ),
                (
                    "complete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"),
                ),
            ],
            options={
                "verbose_name": "资产报修记录",
                "verbose_name_plural": "资产报修记录",
                "db_table": "system_asset_repair",
                "ordering": ["-report_time"],
            },
        ),
        migrations.CreateModel(
            name="BackupPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="策略名称")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "每天"), ("weekly", "每周"), ("monthly", "每月")],
                        max_length=20,
                        verbose_name="执行周期",
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        default=2, help_text="0-23，每天执行的小时", verbose_name="小时"
                    ),
                ),
                (
                    "minute",
                    models.IntegerField(
                        default=0, help_text="0-59，每天执行的分钟", verbose_name="分钟"
                    ),
                ),
                (
                    "week_day",
                    models.IntegerField(
                        default=0, help_text="0-6，每周执行的星期几，0表示周日", verbose_name="星期"
                    ),
                ),
                (
                    "month_day",
                    models.IntegerField(
                        default=1, help_text="1-31，每月执行的日期", verbose_name="日期"
                    ),
                ),
                (
                    "keep_count",
                    models.IntegerField(
                        default=7, help_text="保留最新备份的数量", verbose_name="保留份数"
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "完整备份"),
                            ("incremental", "增量备份"),
                            ("differential", "差异备份"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="备份类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="策略描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "自动备份策略",
                "verbose_name_plural": "自动备份策略",
                "db_table": "system_backup_policy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公文标题")),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="公文编号"),
                ),
                ("content", models.TextField(verbose_name="公文内容")),
                ("summary", models.TextField(blank=True, verbose_name="公文摘要")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("reviewing", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "普通"),
                            ("urgent", "紧急"),
                            ("very_urgent", "特急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="紧急程度",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("internal", "内部"),
                            ("confidential", "机密"),
                            ("secret", "秘密"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="密级",
                    ),
                ),
                (
                    "review_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批截止时间"),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "effective_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失效时间"),
                ),
                ("attachments", models.TextField(blank=True, verbose_name="附件信息")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公文",
                "verbose_name_plural": "公文",
                "db_table": "system_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="分类编码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公文分类",
                "verbose_name_plural": "公文分类",
                "db_table": "system_document_category",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="阅读时间"),
                ),
            ],
            options={
                "verbose_name": "公文阅读记录",
                "verbose_name_plural": "公文阅读记录",
                "db_table": "system_document_read",
            },
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_order", models.IntegerField(verbose_name="审批顺序")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "通过"),
                            ("rejected", "拒绝"),
                            ("returned", "退回修改"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批结果",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "review_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公文审批记录",
                "verbose_name_plural": "公文审批记录",
                "db_table": "system_document_review",
                "ordering": ["review_order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTargetDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "公文目标部门",
                "verbose_name_plural": "公文目标部门",
                "db_table": "system_document_target_departments",
            },
        ),
        migrations.CreateModel(
            name="DocumentTargetUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "公文目标用户",
                "verbose_name_plural": "公文目标用户",
                "db_table": "system_document_target_users",
            },
        ),
        migrations.CreateModel(
            name="MeetingReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="会议主题")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("description", models.TextField(blank=True, verbose_name="会议描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会议室预订",
                "verbose_name_plural": "会议室预订",
                "db_table": "system_meeting_reservation",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("company", "公司公告"),
                            ("system", "系统通知"),
                            ("urgent", "紧急通知"),
                        ],
                        default="company",
                        max_length=20,
                        verbose_name="公告类型",
                    ),
                ),
                ("is_top", models.BooleanField(default=False, verbose_name="是否置顶")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "db_table": "system_notice",
                "ordering": ["-is_top", "-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="NoticeRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="阅读时间"),
                ),
            ],
            options={
                "verbose_name": "公告阅读记录",
                "verbose_name_plural": "公告阅读记录",
                "db_table": "system_notice_read",
            },
        ),
        migrations.CreateModel(
            name="NoticeTargetDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告目标部门",
                "verbose_name_plural": "公告目标部门",
                "db_table": "system_notice_target_departments",
            },
        ),
        migrations.CreateModel(
            name="NoticeTargetUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告目标用户",
                "verbose_name_plural": "公告目标用户",
                "db_table": "system_notice_target_users",
            },
        ),
        migrations.CreateModel(
            name="Seal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="印章名称")),
                (
                    "seal_type",
                    models.CharField(
                        choices=[
                            ("company", "公司公章"),
                            ("contract", "合同专用章"),
                            ("finance", "财务专用章"),
                            ("legal", "法人章"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="印章类型",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="存放位置"),
                ),
                ("description", models.TextField(blank=True, verbose_name="备注")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "印章",
                "verbose_name_plural": "印章",
                "db_table": "system_seal",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SealApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.TextField(verbose_name="用章用途")),
                (
                    "document_title",
                    models.CharField(max_length=200, verbose_name="文件标题"),
                ),
                ("use_date", models.DateField(verbose_name="用章日期")),
                ("copies", models.IntegerField(default=1, verbose_name="份数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("used", "已用章"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"),
                ),
                ("approve_comment", models.TextField(
                    blank=True, verbose_name="审批意见")),
                (
                    "use_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="用章时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用章申请",
                "verbose_name_plural": "用章申请",
                "db_table": "system_seal_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sms", "短信服务"),
                            ("stt", "语音转文本"),
                            ("tts", "文本转语音"),
                            ("ocr", "OCR识别"),
                            ("ai", "AI智能服务"),
                        ],
                        max_length=20,
                        verbose_name="服务类别",
                    ),
                ),
                ("provider", models.CharField(max_length=50, verbose_name="服务商")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API密钥"),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API密钥Secret"
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="接口地址"),
                ),
                (
                    "template_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="模板ID"),
                ),
                (
                    "sign_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="签名名称"),
                ),
                (
                    "request_rate_limit",
                    models.IntegerField(default=0, verbose_name="请求频率限制(次/秒)"),
                ),
                (
                    "max_audio_size",
                    models.BigIntegerField(
                        default=0, verbose_name="最大音频大小(字节)"),
                ),
                (
                    "supported_formats",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="支持格式"),
                ),
                (
                    "extra_config",
                    models.TextField(blank=True, verbose_name="额外配置(JSON格式)"),
                ),
                ("is_enabled", models.BooleanField(
                    default=False, verbose_name="是否启用")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("inactive", "禁用"),
                            ("testing", "测试中"),
                            ("error", "错误"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_test_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后测试时间"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误信息")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "服务配置",
                "verbose_name_plural": "服务配置",
                "db_table": "system_service_config",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="StorageConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("local", "本地存储"),
                            ("aliyun", "阿里云OSS"),
                            ("tencent", "腾讯云COS"),
                            ("huawei", "华为云OBS"),
                            ("baidu", "百度云BOS"),
                            ("qiniu", "七牛云KODO"),
                            ("aws", "AWS S3"),
                            ("feiniu_nas", "飞牛NAS"),
                            ("qunhui_nas", "群晖NAS"),
                            ("webdav", "WebDAV"),
                        ],
                        max_length=50,
                        verbose_name="存储类型",
                    ),
                ),
                ("is_default", models.BooleanField(
                    default=False, verbose_name="是否默认")),
                (
                    "sync_to_local",
                    models.BooleanField(default=False, verbose_name="同步到本地"),
                ),
                (
                    "access_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="AccessKey"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SecretKey"
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="存储桶名称"),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endpoint地址"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="区域"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="访问域名"),
                ),
                (
                    "base_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="基础路径"),
                ),
                (
                    "nas_host",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="NAS主机地址"
                    ),
                ),
                ("nas_port", models.IntegerField(default=0, verbose_name="NAS端口")),
                (
                    "nas_share_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="共享路径"),
                ),
                (
                    "webdav_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="WebDAV地址"
                    ),
                ),
                (
                    "webdav_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WebDAV用户名"
                    ),
                ),
                (
                    "webdav_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WebDAV密码"
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="本地存储路径"),
                ),
                (
                    "max_file_size",
                    models.BigIntegerField(
                        default=0, verbose_name="最大文件大小(字节)"),
                ),
                (
                    "allowed_extensions",
                    models.TextField(blank=True, verbose_name="允许的文件扩展名"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("inactive", "禁用"),
                            ("testing", "测试中"),
                            ("error", "错误"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_test_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后测试时间"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误信息")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "存储配置",
                "verbose_name_plural": "存储配置",
                "db_table": "system_storage_config",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="文件名")),
                (
                    "original_name",
                    models.CharField(max_length=200, verbose_name="原始文件名"),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                ("module", models.CharField(max_length=100, verbose_name="所属模块")),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="关联对象ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "系统附件",
                "verbose_name_plural": "系统附件",
                "db_table": "system_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="备份名称")),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "完整备份"),
                            ("incremental", "增量备份"),
                            ("differential", "差异备份"),
                        ],
                        max_length=20,
                        verbose_name="备份类型",
                    ),
                ),
                ("file_path", models.CharField(
                    max_length=500, verbose_name="备份文件路径")),
                ("file_size", models.BigIntegerField(
                    default=0, verbose_name="文件大小")),
                ("description", models.TextField(blank=True, verbose_name="备份描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="备份时间"),
                ),
            ],
            options={
                "verbose_name": "数据备份",
                "verbose_name_plural": "数据备份",
                "db_table": "system_backup",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("command", models.TextField(verbose_name="执行命令")),
                (
                    "cron_expression",
                    models.CharField(max_length=100, verbose_name="Cron表达式"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("inactive", "禁用"),
                            ("running", "运行中"),
                            ("error", "错误"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后执行时间"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次执行时间"),
                ),
                ("run_count", models.IntegerField(default=0, verbose_name="执行次数")),
                ("error_count", models.IntegerField(
                    default=0, verbose_name="错误次数")),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误信息")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "db_table": "system_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="车牌号"),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="品牌")),
                ("model", models.CharField(max_length=50, verbose_name="型号")),
                ("color", models.CharField(max_length=20, verbose_name="颜色")),
                ("engine_number", models.CharField(
                    max_length=50, verbose_name="发动机号")),
                ("frame_number", models.CharField(
                    max_length=50, verbose_name="车架号")),
                ("purchase_date", models.DateField(verbose_name="购买日期")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="购买价格"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"), ("repair", "维修中"), ("scrap", "报废")],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "insurance_expire",
                    models.DateField(
                        blank=True, null=True, verbose_name="保险到期日"),
                ),
                (
                    "annual_inspection",
                    models.DateField(
                        blank=True, null=True, verbose_name="年检日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "车辆信息",
                "verbose_name_plural": "车辆信息",
                "db_table": "system_vehicle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("fuel", "燃油费"),
                            ("insurance", "保险费"),
                            ("tax", "车船税"),
                            ("parking", "停车费"),
                            ("toll", "过路费"),
                            ("fine", "罚款"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("fee_date", models.DateField(verbose_name="费用日期")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "车辆费用记录",
                "verbose_name_plural": "车辆费用记录",
                "db_table": "system_vehicle_fee",
                "ordering": ["-fee_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[("repair", "维修"), ("maintain", "保养")],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("maintenance_date", models.DateField(verbose_name="维修/保养日期")),
                ("mileage", models.IntegerField(verbose_name="里程数(公里)")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="费用"
                    ),
                ),
                (
                    "service_provider",
                    models.CharField(max_length=200, verbose_name="服务商"),
                ),
                ("description", models.TextField(verbose_name="维修/保养内容")),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="下次保养日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "车辆维修保养记录",
                "verbose_name_plural": "车辆维修保养记录",
                "db_table": "system_vehicle_maintenance",
                "ordering": ["-maintenance_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleOil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oil_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="加油量(升)"
                    ),
                ),
                (
                    "oil_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="加油费用"
                    ),
                ),
                ("mileage", models.IntegerField(verbose_name="里程数(公里)")),
                ("oil_date", models.DateField(verbose_name="加油日期")),
                ("gas_station", models.CharField(
                    max_length=200, verbose_name="加油站")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "车辆油耗记录",
                "verbose_name_plural": "车辆油耗记录",
                "db_table": "system_vehicle_oil",
                "ordering": ["-oil_date"],
            },
        ),
    ]
