# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未完成"), (1, "已完成")], default=0, verbose_name="任务状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
