# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        default="", max_length=100, verbose_name="企业微信userid"
                    ),
                ),
                (
                    "pwd",
                    models.CharField(default="", max_length=100, verbose_name="登录密码"),
                ),
                (
                    "salt",
                    models.CharField(default="", max_length=100, verbose_name="密码盐"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="员工姓名"),
                ),
                (
                    "email",
                    models.CharField(default="", max_length=100, verbose_name="电子邮箱"),
                ),
                (
                    "sip_account",
                    models.CharField(max_length=255, null=True, verbose_name="SIP账号"),
                ),
                (
                    "sip_password",
                    models.CharField(max_length=255, null=True, verbose_name="SIP密码"),
                ),
                (
                    "mobile",
                    models.CharField(default="", max_length=20, verbose_name="手机号码"),
                ),
                ("sex", models.IntegerField(default=0, verbose_name="性别:1男,2女")),
                (
                    "nickname",
                    models.CharField(default="", max_length=100, verbose_name="别名"),
                ),
                ("thumb", models.CharField(max_length=255, verbose_name="头像")),
                (
                    "theme",
                    models.CharField(
                        default="white", max_length=50, verbose_name="系统主题"
                    ),
                ),
                ("did", models.IntegerField(default=0, verbose_name="主部门id")),
                ("pid", models.IntegerField(default=0, verbose_name="上级主管id")),
                ("position_id", models.IntegerField(default=0, verbose_name="职位id")),
                (
                    "position_name",
                    models.CharField(default="", max_length=100, verbose_name="职务"),
                ),
                ("position_rank", models.IntegerField(default=0, verbose_name="职级")),
                (
                    "type",
                    models.CharField(default="", max_length=20, verbose_name="员工类型"),
                ),
                (
                    "is_staff",
                    models.IntegerField(
                        default=1, verbose_name="身份类型:1企业员工,2劳务派遣,3兼职员工"
                    ),
                ),
                (
                    "job_number",
                    models.CharField(default="", max_length=255, verbose_name="工号"),
                ),
                ("birthday", models.IntegerField(default=0, verbose_name="生日")),
                ("age", models.IntegerField(default=0, verbose_name="年龄")),
                ("work_date", models.IntegerField(default=0, verbose_name="开始工作时间")),
                (
                    "work_location",
                    models.CharField(default="", max_length=255, verbose_name="工作地点"),
                ),
                (
                    "native_place",
                    models.CharField(default="", max_length=255, verbose_name="籍贯"),
                ),
                (
                    "nation",
                    models.CharField(default="", max_length=255, verbose_name="民族"),
                ),
                (
                    "home_address",
                    models.CharField(default="", max_length=255, verbose_name="家庭地址"),
                ),
                (
                    "current_address",
                    models.CharField(default="", max_length=255, verbose_name="现居地址"),
                ),
                (
                    "contact",
                    models.CharField(default="", max_length=255, verbose_name="紧急联系人"),
                ),
                (
                    "contact_mobile",
                    models.CharField(
                        default="", max_length=255, verbose_name="紧急联系人电话"
                    ),
                ),
                (
                    "resident_type",
                    models.IntegerField(default=0, verbose_name="户口性质:1农村户口,2城镇户口"),
                ),
                (
                    "resident_place",
                    models.CharField(default="", max_length=255, verbose_name="户口所在地"),
                ),
                (
                    "graduate_school",
                    models.CharField(default="", max_length=255, verbose_name="毕业学校"),
                ),
                ("graduate_day", models.IntegerField(default=0, verbose_name="毕业日期")),
                (
                    "political",
                    models.IntegerField(default=1, verbose_name="政治面貌:1中共党员,2团员"),
                ),
                (
                    "marital_status",
                    models.IntegerField(default=1, verbose_name="婚姻状况:1未婚,2已婚,3离异"),
                ),
                (
                    "idcard",
                    models.CharField(default="", max_length=255, verbose_name="身份证"),
                ),
                (
                    "education",
                    models.CharField(default="", max_length=255, verbose_name="学位"),
                ),
                (
                    "speciality",
                    models.CharField(default="", max_length=255, verbose_name="专业"),
                ),
                (
                    "social_account",
                    models.CharField(default="", max_length=255, verbose_name="社保账号"),
                ),
                (
                    "medical_account",
                    models.CharField(default="", max_length=255, verbose_name="医保账号"),
                ),
                (
                    "provident_account",
                    models.CharField(default="", max_length=255, verbose_name="公积金账号"),
                ),
                (
                    "bank_account",
                    models.CharField(default="", max_length=255, verbose_name="银行卡号"),
                ),
                (
                    "bank_info",
                    models.CharField(default="", max_length=255, verbose_name="开户行"),
                ),
                (
                    "file_ids",
                    models.CharField(default="", max_length=500, verbose_name="档案附件"),
                ),
                ("desc", models.TextField(null=True, verbose_name="员工个人简介")),
                (
                    "is_hide",
                    models.IntegerField(default=0, verbose_name="是否隐藏联系方式:0否,1是"),
                ),
                (
                    "entry_time",
                    models.BigIntegerField(default=0, verbose_name="员工入职日期"),
                ),
                ("create_time", models.BigIntegerField(default=0, verbose_name="注册时间")),
                (
                    "update_time",
                    models.BigIntegerField(default=0, verbose_name="更新信息时间"),
                ),
                (
                    "last_login_time",
                    models.BigIntegerField(default=0, verbose_name="最后登录时间"),
                ),
                ("login_num", models.IntegerField(default=0, verbose_name="登录次数")),
                (
                    "last_login_ip",
                    models.CharField(default="", max_length=64, verbose_name="最后登录IP"),
                ),
                ("is_lock", models.IntegerField(default=0, verbose_name="是否锁屏:1是0否")),
                ("auth_did", models.IntegerField(default=0, verbose_name="数据权限类型")),
                (
                    "auth_dids",
                    models.CharField(default="", max_length=500, verbose_name="可见部门数据"),
                ),
                (
                    "son_dids",
                    models.CharField(
                        default="", max_length=500, verbose_name="可见子部门数据"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=1, verbose_name="状态：-1待入职,0禁止登录,1正常,2离职"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="admin_set",
                        related_query_name="admin",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员",
                "db_table": "mimu_admin",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_id", models.IntegerField(null=True, verbose_name="管理员ID")),
                (
                    "username",
                    models.CharField(max_length=30, null=True, verbose_name="管理员用户名"),
                ),
                (
                    "url",
                    models.CharField(max_length=1500, null=True, verbose_name="操作页面"),
                ),
                (
                    "title",
                    models.CharField(max_length=100, null=True, verbose_name="日志标题"),
                ),
                ("content", models.TextField(null=True, verbose_name="内容")),
                ("ip", models.CharField(max_length=50, null=True, verbose_name="IP")),
                (
                    "user_agent",
                    models.CharField(
                        max_length=255, null=True, verbose_name="User-Agent"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "管理员日志",
                "verbose_name_plural": "管理员日志",
                "db_table": "mimu_admin_log",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="部门名称")),
                ("pid", models.IntegerField(default=0, verbose_name="上级部门ID")),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="GroupExtension",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extension",
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                ("status", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色扩展信息",
                "verbose_name_plural": "角色扩展信息",
                "db_table": "user_groupextension",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=50, verbose_name="职位名称"),
                ),
                ("did", models.IntegerField(default=0, verbose_name="部门ID")),
                (
                    "desc",
                    models.CharField(blank=True, max_length=255, verbose_name="职位描述"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.IntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "职位",
                "verbose_name_plural": "职位",
                "db_table": "mimu_position",
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_configuration",
            },
        ),
        migrations.CreateModel(
            name="SystemOperationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(default="", max_length=255, verbose_name="操作行为"),
                ),
                ("content", models.TextField(null=True, verbose_name="操作内容")),
                (
                    "ip",
                    models.CharField(default="", max_length=64, verbose_name="操作IP"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统操作日志",
                "verbose_name_plural": "系统操作日志",
                "db_table": "system_operation_log",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="模块代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="模块描述")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.systemmodule",
                        verbose_name="父模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "功能模块",
                "verbose_name_plural": "功能模块",
                "db_table": "system_module",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "退出"),
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("view", "查看"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="操作模块")),
                ("action", models.CharField(max_length=200, verbose_name="操作动作")),
                ("content", models.TextField(blank=True, verbose_name="操作内容")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "system_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardPunishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("reward", "奖励"), ("punishment", "惩罚")],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("verbal", "口头"),
                            ("written", "书面"),
                            ("monetary", "经济"),
                            ("promotion", "晋升"),
                            ("demotion", "降级"),
                            ("dismissal", "开除"),
                        ],
                        max_length=20,
                        verbose_name="级别",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("reason", models.TextField(verbose_name="原因")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="金额",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executed_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "奖惩记录",
                "verbose_name_plural": "奖惩记录",
                "db_table": "user_reward_punishment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=255, verbose_name="菜单名称"),
                ),
                (
                    "src",
                    models.CharField(default="", max_length=255, verbose_name="链接地址"),
                ),
                (
                    "icon",
                    models.CharField(default="", max_length=255, verbose_name="图标"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.IntegerField(default=1, verbose_name="状态:1正常,0禁用")),
                (
                    "permission_required",
                    models.CharField(
                        blank=True,
                        help_text="访问该菜单所需的权限，格式为 app_label.codename",
                        max_length=255,
                        verbose_name="所需权限",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联到对应的功能模块，模块禁用时菜单自动隐藏",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.systemmodule",
                        verbose_name="关联功能模块",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submenus",
                        to="user.menu",
                        verbose_name="父级菜单id",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单表",
                "verbose_name_plural": "菜单表",
                "db_table": "mimu_menu",
            },
        ),
        migrations.CreateModel(
            name="EmployeeTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_position", models.CharField(max_length=100, verbose_name="原职位")),
                ("to_position", models.CharField(max_length=100, verbose_name="新职位")),
                ("transfer_reason", models.TextField(verbose_name="调动原因")),
                ("transfer_date", models.DateField(verbose_name="调动日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                ("approve_comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_from",
                        to="department.department",
                        verbose_name="原部门",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_to",
                        to="department.department",
                        verbose_name="调入部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工调动",
                "verbose_name_plural": "员工调动",
                "db_table": "user_employee_transfer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                ("birth_date", models.DateField(verbose_name="出生日期")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(default="汉族", max_length=50, verbose_name="民族"),
                ),
                ("native_place", models.CharField(max_length=200, verbose_name="籍贯")),
                ("address", models.TextField(verbose_name="现住址")),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("primary", "小学"),
                            ("junior", "初中"),
                            ("senior", "高中"),
                            ("college", "大专"),
                            ("bachelor", "本科"),
                            ("master", "硕士"),
                            ("doctor", "博士"),
                        ],
                        max_length=20,
                        verbose_name="学历",
                    ),
                ),
                (
                    "graduate_school",
                    models.CharField(blank=True, max_length=200, verbose_name="毕业院校"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="专业"),
                ),
                (
                    "graduation_date",
                    models.DateField(blank=True, null=True, verbose_name="毕业时间"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "未婚"),
                            ("married", "已婚"),
                            ("divorced", "离异"),
                            ("widowed", "丧偶"),
                        ],
                        max_length=20,
                        verbose_name="婚姻状况",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(max_length=50, verbose_name="紧急联系人"),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=20, verbose_name="紧急联系电话"),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, verbose_name="银行账号"),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="开户银行"),
                ),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=50, verbose_name="社保号"),
                ),
                (
                    "housing_fund_number",
                    models.CharField(blank=True, max_length=50, verbose_name="公积金号"),
                ),
                ("work_experience", models.TextField(blank=True, verbose_name="工作经历")),
                ("skills", models.TextField(blank=True, verbose_name="技能特长")),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工档案",
                "verbose_name_plural": "员工档案",
                "db_table": "user_employee_file",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDimission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimission_type",
                    models.CharField(
                        choices=[
                            ("resignation", "主动离职"),
                            ("dismissal", "被动离职"),
                            ("retirement", "退休"),
                            ("contract_end", "合同到期"),
                        ],
                        max_length=20,
                        verbose_name="离职类型",
                    ),
                ),
                ("dimission_reason", models.TextField(verbose_name="离职原因")),
                ("apply_date", models.DateField(verbose_name="申请日期")),
                ("dimission_date", models.DateField(verbose_name="离职日期")),
                ("handover_content", models.TextField(blank=True, verbose_name="交接内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approve_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                ("approve_comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dimission_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "handover_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handover_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="交接人",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工离职",
                "verbose_name_plural": "员工离职",
                "db_table": "user_employee_dimission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("fixed", "固定期限"),
                            ("unfixed", "无固定期限"),
                            ("project", "项目合同"),
                            ("intern", "实习合同"),
                        ],
                        max_length=20,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, unique=True, verbose_name="合同编号"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本工资"
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="职位")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "生效中"),
                            ("expired", "已到期"),
                            ("terminated", "已终止"),
                            ("renewed", "已续签"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工合同",
                "verbose_name_plural": "员工合同",
                "db_table": "user_employee_contract",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "care_type",
                    models.CharField(
                        choices=[
                            ("birthday", "生日关怀"),
                            ("holiday", "节日关怀"),
                            ("illness", "生病慰问"),
                            ("family", "家庭关怀"),
                            ("achievement", "成就祝贺"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="关怀类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="关怀标题")),
                ("content", models.TextField(verbose_name="关怀内容")),
                ("care_date", models.DateField(verbose_name="关怀日期")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="关怀金额",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executed_cares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工关怀",
                "verbose_name_plural": "员工关怀",
                "db_table": "user_employee_care",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminSecondaryDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.department",
                    ),
                ),
            ],
            options={
                "db_table": "admin_secondary_departments",
                "unique_together": {("admin", "department")},
            },
        ),
        migrations.AddField(
            model_name="admin",
            name="secondary_departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_employees",
                through="user.AdminSecondaryDepartment",
                to="user.department",
                verbose_name="次要部门",
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="admin_set",
                related_query_name="admin",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认角色"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_groups",
                        to="department.department",
                        verbose_name="部门",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_groups",
                        to="auth.group",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门角色关联",
                "verbose_name_plural": "部门角色关联",
                "db_table": "department_group",
                "unique_together": {("department", "group")},
            },
        ),
    ]
