# Generated by Django 4.2.27 on 2026-03-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["sort", "id"],
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
            },
        ),
        migrations.RemoveField(
            model_name="menu",
            name="permission_required",
        ),
        migrations.AlterField(
            model_name="menu",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="user.systemmodule",
                verbose_name="所属模块",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="pid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submenus",
                to="user.menu",
                verbose_name="父级菜单 id",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.IntegerField(default=1, verbose_name="状态:1 正常，0 禁用"),
        ),
        migrations.AlterModelTable(
            name="menu",
            table="system_menu",
        ),
    ]
