# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="未命名部门", max_length=50, verbose_name="部门名称"
                    ),
                ),
                (
                    "pid",
                    models.IntegerField(
                        db_column="pid", default=0, verbose_name="上级部门ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="部门代码"
                    ),
                ),
                (
                    "leader_ids",
                    models.CharField(
                        blank=True,
                        db_column="leader_ids",
                        max_length=500,
                        null=True,
                        verbose_name="部门负责人ID列表",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=60,
                        null=True,
                        verbose_name="部门联系电话",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        null=True,
                        verbose_name="部门描述",
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_column="sort", default=0, verbose_name="排序值"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        db_column="status", default=1, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="create_time", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="update_time", verbose_name="更新时间"
                    ),
                ),
                ("level", models.IntegerField(default=0, verbose_name="部门层级")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "db_table": "department_department",
                "ordering": ["sort", "id"],
            },
        ),
    ]
