# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="库存数量"
                    ),
                ),
                (
                    "locked_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="锁定数量"
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="可用数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总成本"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("locked", "锁定"),
                            ("quarantine", "隔离"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="库存状态",
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                (
                    "last_movement_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后变动日期"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "库存记录",
                "verbose_name_plural": "库存记录",
                "db_table": "inventory_inventory",
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "低库存预警"),
                            ("over_stock", "超库存预警"),
                            ("expiring", "过期预警"),
                            ("slow_moving", "呆滞料预警"),
                            ("reorder", "再订货预警"),
                        ],
                        max_length=20,
                        verbose_name="预警类型",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="当前数量"
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="阈值"
                    ),
                ),
                ("message", models.TextField(verbose_name="预警信息")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "未处理"), (2, "已处理"), (3, "已忽略")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "handle_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                ("handle_remark", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "verbose_name_plural": "库存预警",
                "db_table": "inventory_alert",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="类别编码"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("material", "原材料"),
                            ("product", "产成品"),
                            ("semi", "半成品"),
                            ("pack", "包装物"),
                            ("consumable", "消耗品"),
                            ("other", "其他"),
                        ],
                        default="material",
                        max_length=20,
                        verbose_name="类别类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="类别描述")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")], default=1, verbose_name="状态"
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "库存类别",
                "verbose_name_plural": "库存类别",
                "db_table": "inventory_category",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="物料名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="物料编码"),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, verbose_name="规格型号"),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="计量单位")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=10, verbose_name="重量"
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="长度"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="宽度"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="高度"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=15, verbose_name="体积"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="条形码"),
                ),
                (
                    "qr_code",
                    models.CharField(blank=True, max_length=100, verbose_name="二维码"),
                ),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="标准成本"
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="平均成本"
                    ),
                ),
                (
                    "latest_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="最近成本"
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="零售价格"
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="批发价格"
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最低库存"
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最高库存"
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="再订货点"
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="安全库存"
                    ),
                ),
                ("shelf_life", models.IntegerField(default=0, verbose_name="保质期(天)")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "image",
                    models.CharField(blank=True, max_length=500, verbose_name="物料图片"),
                ),
                ("description", models.TextField(blank=True, verbose_name="物料描述")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "库存物料",
                "verbose_name_plural": "库存物料",
                "db_table": "inventory_item",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("summary", "库存汇总报表"),
                            ("transaction", "库存变动明细报表"),
                            ("turnover", "库存周转报表"),
                            ("valuation", "库存价值报表"),
                            ("age", "库龄分析报表"),
                            ("movement", "出入库统计报表"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                ("report_name", models.CharField(max_length=100, verbose_name="报表名称")),
                ("report_params", models.JSONField(default=dict, verbose_name="报表参数")),
                ("report_data", models.JSONField(default=dict, verbose_name="报表数据")),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="文件路径"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存报表",
                "verbose_name_plural": "库存报表",
                "db_table": "inventory_report",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="采购单号"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("standard", "标准采购"),
                            ("contract", "合同采购"),
                            ("urgent", "紧急采购"),
                            ("blanket", "框架协议"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="订单金额"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="订单数量"
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="已收货金额"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="已收货数量"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="期望到货日期"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际到货日期"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待审核"),
                            (2, "已审核"),
                            (3, "执行中"),
                            (4, "已完成"),
                            (5, "已取消"),
                            (6, "已中止"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="联系电话"),
                ),
                (
                    "delivery_address",
                    models.CharField(blank=True, max_length=500, verbose_name="交货地址"),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, verbose_name="付款条件"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "采购订单",
                "verbose_name_plural": "采购订单",
                "db_table": "inventory_purchase_order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="采购数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="已收货数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="实际成本"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="税率"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="税额"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="期望到货日期"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际到货日期"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "采购订单明细",
                "verbose_name_plural": "采购订单明细",
                "db_table": "inventory_purchase_order_item",
            },
        ),
        migrations.CreateModel(
            name="PurchasePriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="单价"
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="最小订购量"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="失效日期"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "采购价格历史",
                "verbose_name_plural": "采购价格历史",
                "db_table": "inventory_purchase_price_history",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="销售单号"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("standard", "标准销售"),
                            ("contract", "合同销售"),
                            ("urgent", "紧急订单"),
                            ("blanket", "框架协议"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="订单金额"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="订单数量"
                    ),
                ),
                (
                    "shipped_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="已发货金额"
                    ),
                ),
                (
                    "shipped_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="已发货数量"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="期望发货日期"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际发货日期"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待审核"),
                            (2, "已审核"),
                            (3, "已发货"),
                            (4, "已完成"),
                            (5, "已取消"),
                            (6, "已退货"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="联系电话"),
                ),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=500, verbose_name="收货地址"),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, verbose_name="付款条件"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="折扣金额"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="税额"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "销售订单",
                "verbose_name_plural": "销售订单",
                "db_table": "inventory_sales_order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="销售数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "shipped_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="已发货数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="成本单价"
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="成本金额"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="税率"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="税额"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="折扣率"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="期望发货日期"),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际发货日期"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "销售订单明细",
                "verbose_name_plural": "销售订单明细",
                "db_table": "inventory_sales_order_item",
            },
        ),
        migrations.CreateModel(
            name="StockCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="盘点单号"),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("partial", "部分盘点"),
                            ("full", "全仓盘点"),
                            ("cycle", "循环盘点"),
                        ],
                        default="partial",
                        max_length=20,
                        verbose_name="盘点类型",
                    ),
                ),
                ("total_items", models.IntegerField(default=0, verbose_name="盘点项数")),
                ("checked_items", models.IntegerField(default=0, verbose_name="已盘点项数")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待盘点"), (2, "盘点中"), (3, "已完成"), (4, "已取消")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="盘盈金额"
                    ),
                ),
                (
                    "loss_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="盘亏金额"
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="盘点时间"),
                ),
                (
                    "complete_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "盘点单",
                "verbose_name_plural": "盘点单",
                "db_table": "inventory_stock_check",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="系统数量"
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="实盘数量"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="差异数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "difference_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="差异金额"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待盘点"),
                            (2, "已盘点"),
                            (3, "差异"),
                            (4, "盘盈"),
                            (5, "盘亏"),
                        ],
                        default=1,
                        verbose_name="盘点状态",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="盘点时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "盘点单明细",
                "verbose_name_plural": "盘点单明细",
                "db_table": "inventory_stock_check_item",
            },
        ),
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="入库单号"),
                ),
                (
                    "stock_in_type",
                    models.CharField(
                        choices=[
                            ("purchase", "采购入库"),
                            ("production", "生产入库"),
                            ("return", "退货入库"),
                            ("transfer", "调拨入库"),
                            ("other", "其他入库"),
                        ],
                        max_length=20,
                        verbose_name="入库类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总金额"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总数量"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待审核"), (2, "已审核"), (3, "已入库"), (4, "已取消")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "stock_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="入库时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "入库单",
                "verbose_name_plural": "入库单",
                "db_table": "inventory_stock_in",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockInItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="入库数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "入库单明细",
                "verbose_name_plural": "入库单明细",
                "db_table": "inventory_stock_in_item",
            },
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="出库单号"),
                ),
                (
                    "stock_out_type",
                    models.CharField(
                        choices=[
                            ("sale", "销售出库"),
                            ("production", "生产领料"),
                            ("transfer", "调拨出库"),
                            ("scrap", "报废出库"),
                            ("other", "其他出库"),
                        ],
                        max_length=20,
                        verbose_name="出库类型",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总金额"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总数量"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待审核"), (2, "已审核"), (3, "已出库"), (4, "已取消")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "stock_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="出库时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "出库单",
                "verbose_name_plural": "出库单",
                "db_table": "inventory_stock_out",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockOutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="出库数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="金额"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "出库单明细",
                "verbose_name_plural": "出库单明细",
                "db_table": "inventory_stock_out_item",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "入库"),
                            ("stock_out", "出库"),
                            ("transfer", "调拨"),
                            ("adjustment", "调整"),
                            ("check", "盘点"),
                            ("lock", "锁定"),
                            ("unlock", "解锁"),
                            ("return", "退货"),
                            ("scrap", "报废"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(max_length=50, verbose_name="交易编号"),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="交易数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总成本"
                    ),
                ),
                (
                    "before_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="变动前数量"
                    ),
                ),
                (
                    "after_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="变动后数量"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, verbose_name="关联单据类型"),
                ),
                (
                    "reference_id",
                    models.BigIntegerField(default=0, verbose_name="关联单据ID"),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, max_length=50, verbose_name="关联单据编号"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存交易记录",
                "verbose_name_plural": "库存交易记录",
                "db_table": "inventory_stock_transaction",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="调拨单号"),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总数量"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总金额"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待审核"),
                            (2, "已审核"),
                            (3, "调拨中"),
                            (4, "已完成"),
                            (5, "已取消"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "execute_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
                ),
                (
                    "complete_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "调拨单",
                "verbose_name_plural": "调拨单",
                "db_table": "inventory_stock_transfer",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, verbose_name="批次号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="调拨数量"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="单位成本"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "transferred_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="已调拨数量"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "调拨单明细",
                "verbose_name_plural": "调拨单明细",
                "db_table": "inventory_stock_transfer_item",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="仓库编码"),
                ),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("main", "主仓库"),
                            ("branch", "分仓库"),
                            ("virtual", "虚拟仓库"),
                            ("production", "生产仓库"),
                            ("quality", "质检仓库"),
                        ],
                        default="main",
                        max_length=20,
                        verbose_name="仓库类型",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="仓库地址"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="联系电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="电子邮箱"),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="仓库容量"
                    ),
                ),
                (
                    "used_capacity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="已用容量"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认仓库"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "仓库管理",
                "verbose_name_plural": "仓库管理",
                "db_table": "inventory_warehouse",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="库位名称")),
                ("code", models.CharField(max_length=50, verbose_name="库位编码")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("area", "区域"),
                            ("shelf", "货架"),
                            ("layer", "层"),
                            ("bin", "货位"),
                        ],
                        default="area",
                        max_length=20,
                        verbose_name="库位类型",
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="容量"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "禁用")], default=1, verbose_name="状态"
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouselocation",
                        verbose_name="上级库位",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.warehouse",
                        verbose_name="所属仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "库位管理",
                "verbose_name_plural": "库位管理",
                "db_table": "inventory_warehouse_location",
                "ordering": ["warehouse", "code"],
            },
        ),
    ]
