"""
Django settings for dtcall project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a0fqbg6%n+0ze#&6f3@6e&&pp#*_%xg8^@&!z=p3!$t68av6g^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 域名和网络配置
# 允许访问的主机名/IP列表
ALLOWED_HOSTS = [
    'www.dtcall.cn',  # 主域名
    'dtcall.cn',      # 裸域名
    '192.168.1.152',  # 内网IP
    'testserver',     # Django测试服务器
    '*'               # 开发环境使用，生产环境应移除
]

# 代理服务器配置
USE_X_FORWARDED_HOST = True        # 启用代理传递的主机头
USE_X_FORWARDED_PORT = True        # 启用代理传递的端口
FORCE_SCRIPT_NAME = ''             # 应用子路径（如'/app'），默认为根路径
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # HTTPS代理头

# HTTPS设置
# SECURE_SSL_REDIRECT = True  # 强制HTTPS重定向，生产环境应启用

# CSRF信任的源列表
CSRF_TRUSTED_ORIGINS = [
    'https://www.dtcall.cn',  # 主域名
    'https://dtcall.cn',      # 裸域名
    'http://192.168.1.152',   # 内网IP（开发环境）
]

# 认证后端配置
AUTHENTICATION_BACKENDS = [
    'apps.user.auth_backend.AdminAuthBackend',  # 自定义认证后端
    'django.contrib.auth.backends.ModelBackend',  # Django默认认证后端
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition
AUTH_USER_MODEL = 'user.Admin'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.user',
    'apps.customer',
    'apps.finance',
    'apps.common',
    'apps.contract',
    'apps.enterprise',
    'apps.oa',
    'apps.department',
    'apps.project',
    'apps.work',
    'apps.position',
    'apps.home',
    'apps.task',
    'apps.approval',
    'apps.message',
    'apps.spider',
    'apps.disk',
    'apps.system',
    'apps.personal',
    'apps.production',
    'apps.ai',
]

# 原项目验证码配置映射（来自config/captcha.php）
CAPTCHA_LENGTH = 5  # 验证码位数
CAPTCHA_CHALLENGE_FUNCT = 'dtcall.utils.captcha_challenge'  # 自定义字符集合
CAPTCHA_TIMEOUT = 60  # 过期时间（秒）
CAPTCHA_IMAGE_HEIGHT = 60  # 提高图片高度以增加清晰度
CAPTCHA_IMAGE_WIDTH = 200  # 增加图片宽度以容纳更多字符

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'apps.system.middleware.data_permission_middleware.DataPermissionMiddleware',
    'apps.system.middleware.permission_middleware.PermissionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dtcall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            'apps.system.context_processors.get_menus',
            'django.template.context_processors.static',
            'apps.system.context_processors.system_config',
            ],
            'libraries': {
            }
        },
    },
]

WSGI_APPLICATION = 'dtcall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dtcall',  # 数据库名：dtcall
        'USER': 'dtcall',  # 数据库用户名：dtcall
        'PASSWORD': 'dtcall',  # 数据库密码：dtcall
        'HOST': '192.168.1.149',  # 数据库连接地址：192.168.1.149
        'PORT': '5432',  # 数据库端口：5432
        'CONN_MAX_AGE': 300,  # 数据库连接最大保持时间（秒）
        'OPTIONS': {
            'options': '-c search_path=dtcall_schema',
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        }
    }
}


# 登录相关配置
LOGIN_URL = 'user:login'  # 登录页面的URL名称（带user命名空间）
LOGIN_REDIRECT_URL = '/home/main/'  # 登录成功后重定向到主框架页面（包含菜单导航）
LOGOUT_REDIRECT_URL = None  # 完全禁用Django默认登出重定向

# 会话配置
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 使用数据库存储会话，确保会话持久化
SESSION_COOKIE_AGE = 600  # 会话过期时间，单位秒（10分钟）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 浏览器关闭时会话过期
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都会更新会话过期时间，实现从最后一次操作计时

# Password validation


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
# 默认上传大小为5MB，实际大小会在运行时从系统配置中读取
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 增加字段数量限制，解决权限配置时的TooManyFieldsSent错误

# Default primary key field type

# Django REST Framework配置
REST_FRAMEWORK = {
    # 认证类配置
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # 权限类配置
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 分页类配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 渲染器配置
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # 解析器配置
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 过滤类配置
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# 临时文件配置
import tempfile
TEMP_DIR = tempfile.gettempdir()
TEMP_URL = '/temp/'
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 确保日志目录存在
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'error': {
            'format': '{levelname} {asctime} {module} {funcName} {lineno:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 5,
            'formatter': 'detailed',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_error.log'),
            'maxBytes': 1024 * 1024 * 20,  # 20MB
            'backupCount': 10,
            'formatter': 'error',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
        'db_file': {
            'level': 'INFO',  # 将数据库日志级别从DEBUG改为INFO，减少日志量
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_db.log'),
            'maxBytes': 1024 * 1024 * 30,  # 30MB
            'backupCount': 5,
            'formatter': 'detailed',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['db_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.customer.views': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.system.middleware': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}


# AI相关配置
# 语音转文字服务配置
OPENAI_API_KEY = ''  # 留空表示使用免费服务
OPENAI_BASE_URL = 'https://api.openai.com/v1'
BAIDU_API_KEY = ''  # 留空表示使用免费服务
BAIDU_SECRET_KEY = ''  # 留空表示使用免费服务

# 免费语音转文字服务配置
FREE_STT_SERVICE_ENABLED = True  # 启用免费语音转文字服务
FREE_STT_SERVICE_TYPE = 'local'  # 默认使用本地服务

# 本地语音转文字服务配置
LOCAL_STT_MODEL_PATH = ''  # 本地模型路径，留空使用默认配置

# 语音转文字服务默认配置
DEFAULT_STT_SERVICE = 'free'  # 默认使用免费服务
STT_TIMEOUT = 60  # 语音转文字超时时间（秒）
STT_MAX_FILE_SIZE = 25 * 1024 * 1024  # 最大文件大小（25MB）

# 音频文件格式支持
SUPPORTED_AUDIO_FORMATS = ['.wav', '.mp3', '.m4a', '.amr', '.pcm']