"""
Django settings for dtcall project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from apps.system.database_config_utils import normalize_mysql_init_command

BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        _set_env_from_file(key, value)


def _set_env_from_file(key, value):
    key = key.strip()
    value = value.strip().strip('"').strip("'")
    current = os.environ.get(key)
    if current is None or current.strip() == '':
        os.environ[key] = value


_load_env_file()


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_int(name, default=0):
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer') from exc


def _env_list(name, default=None):
    value = os.environ.get(name, '').strip()
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
# 使用环境变量存储 SECRET_KEY，生产环境必须设置此环境变量
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-fallback-key-for-development-only'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False')

# 域名和网络配置
# 允许访问的主机名/IP列表
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
else:
    ALLOWED_HOSTS = [
        'www.dtcall.cn',
        'dtcall.cn',
        'erp.dtcall.cn',
        '192.168.1.152',
        'testserver',
    ]
    if DEBUG:
        ALLOWED_HOSTS.append('*')

# 代理服务器配置
USE_X_FORWARDED_HOST = True        # 启用代理传递的主机头
USE_X_FORWARDED_PORT = True        # 启用代理传递的端口
FORCE_SCRIPT_NAME = ''             # 应用子路径（如'/app'），默认为根路径
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # HTTPS代理头

# URL设置
APPEND_SLASH = False               # 禁用自动添加尾随斜杠，解决附件下载路径问题

# HTTPS和浏览器安全设置。开发环境保持宽松，生产环境(DEBUG=False)默认启用安全策略。
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', not DEBUG)

# CSRF信任的源列表，可通过 CSRF_TRUSTED_ORIGINS 追加或覆盖生产域名。
_default_csrf_trusted_origins = [
    'https://www.dtcall.cn',  # 主域名
    'https://dtcall.cn',      # 裸域名
    'https://erp.dtcall.cn',  # ERP生产域名
    'http://192.168.1.152',   # 内网IP（开发环境）
]
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    _default_csrf_trusted_origins,
)

# 认证后端配置
AUTHENTICATION_BACKENDS = [
    'apps.user.auth_backend.AdminAuthBackend',  # 自定义认证后端
    'django.contrib.auth.backends.ModelBackend',  # Django默认认证后端
]

X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'SAMEORIGIN' if DEBUG else 'DENY')

# Application definition
AUTH_USER_MODEL = 'user.Admin'

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'captcha',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'apps.user.apps.UserConfig',
    'apps.customer',
    'apps.finance',
    'apps.common',
    'apps.contract',
    'apps.enterprise',
    'apps.oa',
    'apps.department',
    'apps.project',
    'apps.work',
    'apps.position',
    'apps.home',
    'apps.task',
    'apps.approval',
    'apps.message',
    'apps.spider',
    'apps.disk',
    'apps.system.apps.SystemConfig',
    'apps.personal',
    'apps.production',
    'apps.ai',
    'apps.ai_orchestrator',
    'apps.inventory',
    'apps.hrbp',
]

# 验证码配置
CAPTCHA_CHALLENGE_FUNCT = 'dtcall.utils.captcha_challenge'  # 使用加法验证码
CAPTCHA_TIMEOUT = 60  # 验证码有效期（秒）
CAPTCHA_IMAGE_HEIGHT = 50  # 图片高度
CAPTCHA_IMAGE_WIDTH = 180  # 图片宽度

CAPTCHA_LETTER_ROTATION = False

#CAPTCHA_NOISE_FUNCTIONS = ()  # 禁用噪点
#CAPTCHA_FILTER_FUNCTIONS = ()  # 禁用滤波

CAPTCHA_FOREGROUND_COLOR = '#001100'  # 深绿色前景
CAPTCHA_BACKGROUND_COLOR = '#FFFFFF'  # 白色背景

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'apps.system.middleware.session_middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'apps.system.middleware.database_setup_middleware.DatabaseSetupMiddleware',
    'apps.system.middleware.data_permission_middleware.DataPermissionMiddleware',
    'apps.system.middleware.permission_middleware.PermissionMiddleware',
    'apps.system.middleware.operation_log_middleware.OperationLogMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dtcall.urls'
ASGI_APPLICATION = 'dtcall.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            'apps.system.context_processors.get_menus',
            'django.template.context_processors.static',
            'apps.system.context_processors.system_config',
                'apps.system.context_processors.system_version',
            ],
            'libraries': {
            }
        },
    },
]

REDIS_HOST = os.environ.get('REDIS_HOST', '').strip()
REDIS_PORT = os.environ.get('REDIS_PORT', '6379').strip()
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '').strip()
if REDIS_HOST:
    try:
        import channels_redis  # noqa: F401
        _redis_auth = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [f"redis://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/2"],
                },
            },
        }
    except ImportError:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer",
            },
        }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

if REDIS_HOST:
    _redis_auth = f":{REDIS_PASSWORD}@" if REDIS_PASSWORD else ""
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/1",
            "TIMEOUT": 300,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 50,
                    "retry_on_timeout": True,
                },
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "dtcall-default-cache",
            "TIMEOUT": 300,
            "OPTIONS": {
                "MAX_ENTRIES": 1000,
                "CULL_FREQUENCY": 3,
            }
        }
    }

WSGI_APPLICATION = 'dtcall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE_ALIASES = {
    'sqlite': 'django.db.backends.sqlite3',
    'sqlite3': 'django.db.backends.sqlite3',
    'postgres': 'django.db.backends.postgresql',
    'postgresql': 'django.db.backends.postgresql',
    'pgsql': 'django.db.backends.postgresql',
    'psql': 'django.db.backends.postgresql',
    'mysql': 'django.db.backends.mysql',
    'mariadb': 'django.db.backends.mysql',
}


def _resolve_database_engine(value):
    engine = (value or '').strip()
    if not engine:
        return ''
    normalized = engine.lower()
    if normalized in DATABASE_ENGINE_ALIASES:
        return DATABASE_ENGINE_ALIASES[normalized]
    if engine.startswith('django.db.backends.'):
        return engine
    raise ImproperlyConfigured(
        f'Unsupported DATABASE_ENGINE "{engine}". '
        'Use sqlite, postgresql, mysql, mariadb, or a django.db.backends.* path.'
    )


def _database_options(engine):
    options = {}
    connect_timeout = _env_int('DATABASE_CONNECT_TIMEOUT', 0)
    if connect_timeout:
        options['connect_timeout'] = connect_timeout
    if engine == 'django.db.backends.mysql':
        options.update({
            'charset': os.environ.get('MYSQL_CHARSET', 'utf8mb4'),
            'init_command': normalize_mysql_init_command(
                os.environ.get('MYSQL_INIT_COMMAND'),
            ),
        })
    return options


def _sqlite_name(name):
    if not name:
        return BASE_DIR / 'db.sqlite3'
    if name == ':memory:':
        return name
    path = Path(name)
    return path if path.is_absolute() else BASE_DIR / path


def _is_test_command():
    return any(arg == 'test' or arg.endswith('.test') for arg in sys.argv[1:3])


def _database_from_url(database_url):
    parsed = urlparse(database_url)
    engine = _resolve_database_engine(parsed.scheme.split('+', 1)[0])
    if engine == 'django.db.backends.sqlite3':
        return {
            'ENGINE': engine,
            'NAME': _sqlite_name(unquote(parsed.path.lstrip('/'))),
        }

    query_options = dict(parse_qsl(parsed.query))
    config = {
        'ENGINE': engine,
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
        'CONN_MAX_AGE': _env_int('DATABASE_CONN_MAX_AGE', 1800),
        'CONN_HEALTH_CHECKS': _env_bool('DATABASE_CONN_HEALTH_CHECKS', True),
    }
    options = _database_options(engine)
    options.update(query_options)
    if options:
        config['OPTIONS'] = options
    return config


def _database_from_env():
    raw_engine = (
        os.environ.get('DATABASE_ENGINE', '').strip()
        or os.environ.get('DATABASE_TYPE', '').strip()
        or os.environ.get('DB_ENGINE', '').strip()
    )
    engine = _resolve_database_engine(raw_engine) if raw_engine else ''
    database_url = os.environ.get('DATABASE_URL', '').strip()
    if database_url and engine != 'django.db.backends.sqlite3':
        return _database_from_url(database_url)

    host = os.environ.get('DATABASE_HOST', '').strip()
    if not engine:
        if not host:
            if _is_test_command():
                return {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': _sqlite_name(''),
                }
            return {
                'ENGINE': 'django.db.backends.dummy',
            }
        engine = 'django.db.backends.postgresql'

    name = os.environ.get('DATABASE_NAME', '').strip()
    if engine == 'django.db.backends.sqlite3':
        sqlite_name = name if raw_engine else ''
        return {
            'ENGINE': engine,
            'NAME': _sqlite_name(sqlite_name),
        }

    default_port = '3306' if engine == 'django.db.backends.mysql' else '5432'
    config = {
        'ENGINE': engine,
        'NAME': name or 'dtcall',
        'USER': os.environ.get('DATABASE_USER', '').strip() or 'dtcall_user',
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', '').strip(),
        'HOST': host or '127.0.0.1',
        'PORT': os.environ.get('DATABASE_PORT', '').strip() or default_port,
        'CONN_MAX_AGE': _env_int('DATABASE_CONN_MAX_AGE', 1800),
        'CONN_HEALTH_CHECKS': _env_bool('DATABASE_CONN_HEALTH_CHECKS', True),
    }
    options = _database_options(engine)
    if options:
        config['OPTIONS'] = options
    return config


DATABASES = {
    'default': _database_from_env(),
}


# 登录相关配置
LOGIN_URL = 'user:login'  # 登录页面的URL名称（带user命名空间）
LOGIN_REDIRECT_URL = '/home/main/'  # 登录成功后重定向到主框架页面（包含菜单导航）
LOGOUT_REDIRECT_URL = None  # 完全禁用Django默认登出重定向

# 会话配置
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 7200  # 会话过期时间，单位秒（2小时）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 浏览器关闭时不过期，配合SESSION_COOKIE_AGE使用
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都会更新会话过期时间，实现从最后一次操作计时

# Password validation


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # 最小8位密码
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
# 默认上传大小为5MB，实际大小会在运行时从系统配置中读取
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 增加字段数量限制，解决权限配置时的TooManyFieldsSent错误

# Default primary key field type

# Django REST Framework配置
REST_FRAMEWORK = {
    # 认证类配置
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # 权限类配置
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 分页类配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
    # 渲染器配置
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # 解析器配置
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 过滤类配置
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# 临时文件配置
import tempfile
TEMP_DIR = tempfile.gettempdir()
TEMP_URL = '/temp/'
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 确保日志目录存在
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'error': {
            'format': '{levelname} {asctime} {module} {funcName} {lineno:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 5,
            'formatter': 'detailed',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_error.log'),
            'maxBytes': 1024 * 1024 * 20,  # 20MB
            'backupCount': 10,
            'formatter': 'error',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
        'db_file': {
            'level': 'INFO',  # 将数据库日志级别从DEBUG改为INFO，减少日志量
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django_db.log'),
            'maxBytes': 1024 * 1024 * 30,  # 30MB
            'backupCount': 5,
            'formatter': 'detailed',
            'encoding': 'utf-8',
            'delay': True,  # 延迟文件打开，直到第一次写入
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['db_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps.customer.views': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.system.middleware': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}


# AI相关配置
# 语音转文字服务配置
OPENAI_API_KEY = ''  # 留空表示使用免费服务
OPENAI_BASE_URL = 'https://api.openai.com/v1'
BAIDU_API_KEY = ''  # 留空表示使用免费服务
BAIDU_SECRET_KEY = ''  # 留空表示使用免费服务

# 免费语音转文字服务配置
FREE_STT_SERVICE_ENABLED = True  # 启用免费语音转文字服务
FREE_STT_SERVICE_TYPE = 'local'  # 默认使用本地服务

# 本地语音转文字服务配置
LOCAL_STT_MODEL_PATH = ''  # 本地模型路径，留空使用默认配置

# 语音转文字服务默认配置
DEFAULT_STT_SERVICE = 'free'  # 默认使用免费服务
STT_TIMEOUT = 60  # 语音转文字超时时间（秒）
STT_MAX_FILE_SIZE = 25 * 1024 * 1024  # 最大文件大小（25MB）

# 音频文件格式支持
SUPPORTED_AUDIO_FORMATS = ['.wav', '.mp3', '.m4a', '.amr', '.pcm']

# AI配置自动加载开关（迁移时设置为False以避免数据库不存在错误）
AI_AUTO_LOAD_CONFIG = True
