# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField(verbose_name="关联对象ID")),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "comment",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="项目编号"),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="项目预算"
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="实际成本"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "未设置"),
                            (1, "未开始"),
                            (2, "进行中"),
                            (3, "已完成"),
                            (4, "已关闭"),
                            (5, "已暂停"),
                        ],
                        default=1,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="完成进度(%)"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "project",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="颜色标识"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目分类",
                "verbose_name_plural": "项目分类",
                "db_table": "basedata_project_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文档标题")),
                ("content", models.TextField(blank=True, verbose_name="文档内容")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="文件路径"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "项目文档",
                "verbose_name_plural": "项目文档",
                "db_table": "project_document",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="阶段名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="阶段代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="阶段描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目阶段",
                "verbose_name_plural": "项目阶段",
                "db_table": "basedata_project_stage",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="阶段名称")),
                ("description", models.TextField(blank=True, verbose_name="阶段描述")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="结束日期"),
                ),
                ("sort", models.SmallIntegerField(default=0, verbose_name="排序")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否当前阶段"),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="完成进度(%)"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目阶段",
                "verbose_name_plural": "项目阶段",
                "db_table": "project_step",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="预估工时(小时)"),
                ),
                (
                    "actual_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="实际工时(小时)"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "未开始"),
                            (2, "进行中"),
                            (3, "已完成"),
                            (4, "已延期"),
                            (5, "已取消"),
                        ],
                        default=1,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="完成进度(%)"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "task",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类别代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="类别描述")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="小时费率",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "工作类别",
                "verbose_name_plural": "工作类别",
                "db_table": "basedata_work_type",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="工作日期")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="工作时长(小时)"
                    ),
                ),
                ("description", models.TextField(
                    blank=True, verbose_name="工作内容描述")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_hours",
                        to="project.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "工时记录",
                "verbose_name_plural": "工时记录",
                "db_table": "work_hour",
                "ordering": ["-work_date", "-create_time"],
            },
        ),
    ]
