# Generated by Django 5.2.15 on 2026-07-02 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRiskAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="风险等级"
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="风险得分"),
                ),
                (
                    "warning_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="预警数量"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="分析摘要")),
                (
                    "key_risks",
                    models.JSONField(blank=True, default=list, verbose_name="关键风险点"),
                ),
                (
                    "suggestions",
                    models.JSONField(blank=True, default=list, verbose_name="建议措施"),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        default="manual_review", max_length=50, verbose_name="推荐动作"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=5, verbose_name="置信度"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="指标快照"),
                ),
                (
                    "analysis_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="标准化分析结果"),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[("manual", "手动触发"), ("scheduled", "每日巡检")],
                        default="manual",
                        max_length=20,
                        verbose_name="触发来源",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="分析时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_analyses",
                        to="project.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_project_risk_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目风险分析",
                "verbose_name_plural": "项目风险分析",
                "db_table": "project_risk_analysis",
                "ordering": ["-analyzed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "analyzed_at"],
                        name="project_ris_project_b18dc8_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "analyzed_at"],
                        name="project_ris_risk_le_02c7f3_idx",
                    ),
                ],
            },
        ),
    ]
