# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
        ('finance_new', '0001_initial'),
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='报销人'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='报销部门'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='付款人'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance_new.expensecategory', verbose_name='父类别'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_new.expensecategory', verbose_name='报销类别'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_new.expensecategory', verbose_name='费用类别'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance_new.expense', verbose_name='报销申请'),
        ),
        migrations.AddField(
            model_name='income',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_incomes', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customercontract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='申请部门'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='开票人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance_new.invoice', verbose_name='关联发票'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance_new.expense', verbose_name='关联报销'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['code'], name='idx_exp_cat_code_new'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['parent'], name='idx_exp_cat_parent_new'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['status'], name='idx_exp_cat_status_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['code'], name='idx_expense_code_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['applicant'], name='idx_expense_applicant_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['approval_status'], name='idx_expense_approval_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_status'], name='idx_expense_payment_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='idx_expense_date_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['department'], name='idx_expense_dept_new'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project'], name='idx_expense_project_new'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['expense'], name='idx_exp_item_expense_new'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['category'], name='idx_exp_item_category_new'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['expense_date'], name='idx_exp_item_date_new'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['code'], name='idx_invoice_code_new'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='idx_invoice_customer_new'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_status'], name='idx_invoice_status_new'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['approval_status'], name='idx_invoice_approval_new'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['enter_status'], name='idx_invoice_enter_new'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['invoice'], name='idx_income_invoice_new'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_date'], name='idx_income_date_new'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['expense'], name='idx_payment_expense_new'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date_new'),
        ),
    ]
