# Generated by Django 4.2.27 on 2026-03-04 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField(default=0, verbose_name="父协议id")),
                (
                    "code",
                    models.CharField(
                        default="", max_length=255, verbose_name="合同编号"),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="合同名称"),
                ),
                ("cate_id", models.IntegerField(default=0, verbose_name="分类id")),
                (
                    "types",
                    models.SmallIntegerField(
                        default=1, verbose_name="合同性质:1普通合同2商品合同3服务合同"
                    ),
                ),
                (
                    "subject_id",
                    models.CharField(
                        default="", max_length=255, verbose_name="签约主体"),
                ),
                ("customer_id", models.IntegerField(
                    default=0, verbose_name="关联客户ID")),
                (
                    "customer",
                    models.CharField(
                        default="", max_length=255, verbose_name="客户名称"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="客户代表"),
                ),
                (
                    "contact_mobile",
                    models.CharField(
                        default="", max_length=255, verbose_name="客户电话"),
                ),
                (
                    "contact_address",
                    models.CharField(
                        default="", max_length=255, verbose_name="客户地址"),
                ),
                (
                    "start_time",
                    models.BigIntegerField(default=0, verbose_name="合同开始时间"),
                ),
                ("end_time", models.BigIntegerField(
                    default=0, verbose_name="合同结束时间")),
                ("admin_id", models.IntegerField(default=0, verbose_name="创建人")),
                ("prepared_uid", models.IntegerField(
                    default=0, verbose_name="合同制定人")),
                ("sign_uid", models.IntegerField(default=0, verbose_name="合同签订人")),
                ("keeper_uid", models.IntegerField(
                    default=0, verbose_name="合同保管人")),
                (
                    "share_ids",
                    models.CharField(
                        default="", max_length=500, verbose_name="共享人员ID"),
                ),
                (
                    "file_ids",
                    models.CharField(
                        default="", max_length=500, verbose_name="相关附件ID"),
                ),
                ("sign_time", models.BigIntegerField(
                    default=0, verbose_name="合同签订时间")),
                ("did", models.IntegerField(default=0, verbose_name="合同所属部门")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="合同金额",
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="合同内容")),
                (
                    "is_tax",
                    models.SmallIntegerField(
                        default=0, verbose_name="是否含税：0未含税,1含税"),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, verbose_name="税点"
                    ),
                ),
                ("stop_uid", models.IntegerField(default=0, verbose_name="中止人")),
                ("stop_time", models.BigIntegerField(
                    default=0, verbose_name="中止时间")),
                ("stop_remark", models.TextField(
                    default="", verbose_name="中止备注信息")),
                ("void_uid", models.IntegerField(default=0, verbose_name="作废人")),
                ("void_time", models.BigIntegerField(
                    default=0, verbose_name="作废时间")),
                ("void_remark", models.TextField(
                    default="", verbose_name="作废备注信息")),
                ("archive_uid", models.IntegerField(
                    default=0, verbose_name="归档人")),
                (
                    "archive_time",
                    models.BigIntegerField(default=0, verbose_name="归档时间"),
                ),
                ("remark", models.TextField(default="", verbose_name="备注信息")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.BigIntegerField(
                        default=0,
                        help_text="原表bigint NOT NULL DEFAULT 0",
                        verbose_name="删除时间",
                    ),
                ),
                (
                    "check_status",
                    models.SmallIntegerField(
                        default=0, verbose_name="审核状态:0待审核,1审核中,2审核通过,3审核不通过,4撤销审核"
                    ),
                ),
                (
                    "check_flow_id",
                    models.IntegerField(default=0, verbose_name="审核流程id"),
                ),
                (
                    "check_step_sort",
                    models.IntegerField(default=0, verbose_name="当前审批步骤"),
                ),
                (
                    "check_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="当前审批人ID"
                    ),
                ),
                (
                    "check_last_uid",
                    models.CharField(
                        default="", max_length=500, verbose_name="上一审批人"),
                ),
                (
                    "check_history_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="历史审批人ID"
                    ),
                ),
                (
                    "check_copy_uids",
                    models.CharField(
                        default="", max_length=500, verbose_name="抄送人ID"),
                ),
                (
                    "check_time",
                    models.BigIntegerField(default=0, verbose_name="审核通过时间"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "销售合同",
                "verbose_name_plural": "销售合同",
                "db_table": "mimu_contract",
            },
        ),
        migrations.CreateModel(
            name="ContractCate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=100, verbose_name="合同类别名称"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=1, verbose_name="状态：-1删除 0禁用 1启用"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.BigIntegerField(
                        default=0,
                        help_text="原表bigint NOT NULL DEFAULT 0",
                        verbose_name="删除时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同类别",
                "verbose_name_plural": "合同类别",
                "db_table": "mimu_contract_cate",
            },
        ),
        migrations.CreateModel(
            name="ContractCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="分类代码"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "template_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="合同模板路径"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "合同分类",
                "verbose_name_plural": "合同分类",
                "db_table": "basedata_contract_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="产品名称"),
                ),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, verbose_name="产品编码"),
                ),
                (
                    "specs",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="产品规格"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="单位"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "合同产品",
                "verbose_name_plural": "合同产品",
                "db_table": "contract_product",
            },
        ),
        migrations.CreateModel(
            name="ProductCate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=50, verbose_name="分类名称"),
                ),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "合同产品分类",
                "verbose_name_plural": "合同产品分类",
                "db_table": "contract_product_cate",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "产品分类",
                "verbose_name_plural": "产品分类",
                "db_table": "basedata_product_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="采购名称"),
                ),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, verbose_name="采购编号"),
                ),
                ("types", models.SmallIntegerField(
                    default=0, verbose_name="采购类型")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0)],
                        verbose_name="采购金额",
                    ),
                ),
                ("sign_time", models.DateField(verbose_name="签订日期")),
                ("start_time", models.DateField(verbose_name="开始日期")),
                ("end_time", models.DateField(verbose_name="结束日期")),
                (
                    "share_ids",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="共享人员ID"),
                ),
                (
                    "check_status",
                    models.SmallIntegerField(default=0, verbose_name="审核状态"),
                ),
                (
                    "check_uids",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="待审核人员ID"
                    ),
                ),
                (
                    "check_history_uids",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="已审核人员ID"
                    ),
                ),
                (
                    "file_ids",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="附件ID"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "archive_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归档时间"),
                ),
                (
                    "stop_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="终止时间"),
                ),
                (
                    "void_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="作废时间"),
                ),
            ],
            options={
                "verbose_name": "合同采购",
                "verbose_name_plural": "合同采购",
                "db_table": "contract_purchase",
            },
        ),
        migrations.CreateModel(
            name="PurchaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "采购品分类",
                "verbose_name_plural": "采购品分类",
                "db_table": "basedata_purchase_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="采购品名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="采购品代码"),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="规格型号"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="计量单位"),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="参考价格",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="采购品描述")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "采购品",
                "verbose_name_plural": "采购品",
                "db_table": "basedata_purchase_item",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="服务名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="服务代码"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="计量单位"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="服务价格",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="服务周期(天)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="服务描述")),
                ("requirements", models.TextField(blank=True, verbose_name="服务要求")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "服务内容",
                "verbose_name_plural": "服务内容",
                "db_table": "basedata_service",
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "服务分类",
                "verbose_name_plural": "服务分类",
                "db_table": "basedata_service_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=100, verbose_name="服务名称"),
                ),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, verbose_name="服务编码"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="单位"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "合同服务",
                "verbose_name_plural": "合同服务",
                "db_table": "contract_services",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="供应商名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="供应商代码"),
                ),
                ("contact_person", models.CharField(
                    max_length=50, verbose_name="联系人")),
                ("contact_phone", models.CharField(
                    max_length=50, verbose_name="联系电话")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="地址"),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="税号"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="银行账号"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="开户银行"),
                ),
                (
                    "credit_level",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="信用等级"),
                ),
                ("business_scope", models.TextField(
                    blank=True, verbose_name="经营范围")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "db_table": "basedata_supplier",
            },
        ),
    ]
