# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='productcate',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.productcate', verbose_name='父级分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.productcate', verbose_name='产品分类'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='archive_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_archive', to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractcate', verbose_name='采购分类'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='keeper_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_keeper', to=settings.AUTH_USER_MODEL, verbose_name='保管人'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='prepared_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_prepared', to=settings.AUTH_USER_MODEL, verbose_name='编制人'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='sign_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_sign', to=settings.AUTH_USER_MODEL, verbose_name='签订人'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stop_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_stop', to=settings.AUTH_USER_MODEL, verbose_name='终止人'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='void_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_void', to=settings.AUTH_USER_MODEL, verbose_name='作废人'),
        ),
        migrations.AddField(
            model_name='services',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
