# Generated by Django 4.2.27 on 2026-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="ai_key_terms",
            field=models.JSONField(blank=True, default=list, verbose_name="AI提取关键条款"),
        ),
        migrations.AddField(
            model_name="contract",
            name="ai_risk_level",
            field=models.CharField(
                default="unknown", max_length=20, verbose_name="AI风险评级(高/中/低)"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="ai_risk_points",
            field=models.JSONField(blank=True, default=list, verbose_name="AI识别风险点"),
        ),
    ]
