# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_contract_ai_key_terms_contract_ai_risk_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="scan_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contract_scans/%Y/%m/",
                verbose_name="合同扫描件",
            ),
        ),
    ]
