# Generated by Django 5.2.1 on 2026-06-30 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0004_contract_scan_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAIReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_version", models.IntegerField(default=1, verbose_name="审查版本")),
                (
                    "contract_info",
                    models.JSONField(blank=True, default=dict, verbose_name="合同信息摘要"),
                ),
                (
                    "overall_risk_level",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="总体风险评级"
                    ),
                ),
                (
                    "overall_summary",
                    models.TextField(default="", verbose_name="总体评估意见"),
                ),
                (
                    "clause_reviews",
                    models.JSONField(blank=True, default=list, verbose_name="逐条审查意见"),
                ),
                (
                    "review_conclusion",
                    models.JSONField(blank=True, default=list, verbose_name="审查结论汇总"),
                ),
                (
                    "final_recommendation",
                    models.TextField(default="", verbose_name="最终建议"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="审查时间"),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, default="", verbose_name="AI原始响应"),
                ),
                ("is_latest", models.BooleanField(default=True, verbose_name="是否最新版本")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reviews",
                        to="contract.contract",
                        verbose_name="关联合同",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审查人",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI合同审查记录",
                "verbose_name_plural": "AI合同审查记录",
                "db_table": "contract_ai_review",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractDiffRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compare_file",
                    models.FileField(
                        upload_to="contract_diffs/%Y/%m/", verbose_name="对比文件"
                    ),
                ),
                ("original_text", models.TextField(default="", verbose_name="原始文本")),
                ("compare_text", models.TextField(default="", verbose_name="对比文本")),
                (
                    "diff_result",
                    models.JSONField(blank=True, default=list, verbose_name="差异结果"),
                ),
                (
                    "risk_flags",
                    models.JSONField(blank=True, default=list, verbose_name="风险标记"),
                ),
                (
                    "compared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="比对时间"),
                ),
                (
                    "compared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="比对人",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diff_records",
                        to="contract.contract",
                        verbose_name="关联合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同差异比对记录",
                "verbose_name_plural": "合同差异比对记录",
                "db_table": "contract_diff_record",
                "ordering": ["-compared_at"],
            },
        ),
    ]
