# Generated by Django 5.2.1 on 2026-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0005_add_ai_review_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractaireview",
            name="data_cross_check",
            field=models.JSONField(blank=True, default=list, verbose_name="数据交叉校验结果"),
        ),
    ]
