# Generated by Django 5.2.15 on 2026-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0008_purchase_project_relation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractlegalconsultrecord",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "AI法律咨询记录",
                "verbose_name_plural": "AI法律咨询记录",
            },
        ),
        migrations.AddField(
            model_name="contractaireview",
            name="review_type",
            field=models.CharField(
                choices=[("full", "完整审查"), ("quick", "快速评估")],
                default="full",
                max_length=20,
                verbose_name="审查类型",
            ),
        ),
    ]
