# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(default=0, verbose_name='所在文件夹目录ID')),
                ('types', models.PositiveSmallIntegerField(default=0, help_text='0文件,1在线文档,2文件夹', verbose_name='类型')),
                ('action_id', models.PositiveIntegerField(default=0, verbose_name='相关联id')),
                ('name', models.CharField(default='', max_length=200, verbose_name='文件名称')),
                ('file_ext', models.CharField(default='', max_length=200, verbose_name='文件后缀名称')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('is_star', models.PositiveSmallIntegerField(default=0, verbose_name='重要与否')),
                ('is_share', models.PositiveSmallIntegerField(default=0, verbose_name='共享与否')),
                ('share_dids', models.CharField(default='', max_length=200, verbose_name='共享部门')),
                ('share_ids', models.CharField(default='', max_length=200, verbose_name='共享人')),
                ('admin_id', models.PositiveIntegerField(default=0, verbose_name='创建人')),
                ('did', models.PositiveIntegerField(default=0, verbose_name='所属部门')),
                ('create_time', models.PositiveBigIntegerField(default=0, verbose_name='创建时间')),
                ('update_time', models.PositiveBigIntegerField(default=0, verbose_name='修改时间')),
                ('delete_time', models.PositiveBigIntegerField(default=0, verbose_name='删除时间')),
                ('clear_time', models.PositiveBigIntegerField(default=0, verbose_name='清除时间')),
            ],
            options={
                'verbose_name': '网盘表',
                'verbose_name_plural': '网盘表',
                'db_table': 'mimu_disk',
            },
        ),
        migrations.CreateModel(
            name='DiskFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件夹名称')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('permission_level', models.IntegerField(choices=[(1, '只读'), (2, '读写'), (3, '管理')], default=1, verbose_name='权限级别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '网盘文件夹',
                'verbose_name_plural': '网盘文件夹',
                'db_table': 'disk_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiskOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('upload', '上传'), ('download', '下载'), ('delete', '删除'), ('share', '分享'), ('move', '移动'), ('copy', '复制'), ('rename', '重命名')], max_length=20, verbose_name='操作类型')),
                ('description', models.CharField(max_length=500, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.CharField(max_length=500, verbose_name='用户代理')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '文件操作日志',
                'verbose_name_plural': '文件操作日志',
                'db_table': 'disk_operation',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DiskShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('file', '文件'), ('folder', '文件夹')], max_length=10, verbose_name='分享类型')),
                ('share_code', models.CharField(max_length=20, unique=True, verbose_name='分享码')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='提取密码')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('permission_type', models.CharField(choices=[('view', '仅查看'), ('download', '可下载'), ('edit', '可编辑')], default='download', max_length=10, verbose_name='权限类型')),
                ('allow_download', models.BooleanField(default=True, verbose_name='允许下载')),
                ('access_limit', models.IntegerField(default=0, verbose_name='访问次数限制(0为无限制)')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('download_limit', models.IntegerField(default=0, verbose_name='下载限制(0为无限制)')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('visitor_ips', models.TextField(blank=True, verbose_name='访问者IP记录')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件分享',
                'verbose_name_plural': '文件分享',
                'db_table': 'disk_share',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DiskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('original_name', models.CharField(max_length=200, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_ext', models.CharField(default='', max_length=20, verbose_name='文件扩展名')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('mime_type', models.CharField(default='', max_length=100, verbose_name='MIME类型')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_starred', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '网盘文件',
                'verbose_name_plural': '网盘文件',
                'db_table': 'disk_file',
                'ordering': ['-update_time'],
            },
        ),
    ]
