# Generated by Django for preview functionality enhancement

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskfile',
            name='preview_count',
            field=models.IntegerField(default=0, verbose_name='预览次数'),
        ),
        migrations.AddField(
            model_name='diskfile',
            name='last_preview_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后预览时间'),
        ),
    ]
