# Generated by Django 4.2.27 on 2026-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disk", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diskfile",
            name="ai_content_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI提取文本(OCR/解析)"
            ),
        ),
        migrations.AddField(
            model_name="diskfile",
            name="ai_status",
            field=models.IntegerField(
                default=0, verbose_name="AI处理状态:0未处理,1处理中,2已完成,3失败"
            ),
        ),
        migrations.AddField(
            model_name="diskfile",
            name="ai_summary",
            field=models.TextField(blank=True, null=True, verbose_name="AI智能摘要"),
        ),
        migrations.AddField(
            model_name="diskfile",
            name="ai_tags",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="AI智能标签"
            ),
        ),
    ]
