# Generated by Django 5.2.5 on 2026-01-06 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='触发名称')),
                ('action_type', models.CharField(choices=[('send_message', '发送消息'), ('create_task', '创建任务'), ('send_email', '发送邮件'), ('send_sms', '发送短信'), ('add_contact', '添加联系人'), ('share_document', '分享文档'), ('other', '其他')], max_length=20, verbose_name='行动类型')),
                ('conditions', models.JSONField(verbose_name='触发条件')),
                ('config', models.JSONField(verbose_name='行动配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI自动行动触发',
                'verbose_name_plural': 'AI自动行动触发',
                'db_table': 'ai_action_trigger',
            },
        ),
        migrations.CreateModel(
            name='AIBatchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='测试名称')),
                ('description', models.TextField(blank=True, verbose_name='测试描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '运行中'), ('completed', '已完成'), ('paused', '已暂停')], default='draft', max_length=20, verbose_name='测试状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('traffic_allocation', models.JSONField(help_text='如：{"variant_a": 50, "variant_b": 50}', verbose_name='流量分配')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI A/B测试',
                'verbose_name_plural': 'AI A/B测试',
                'db_table': 'ai_ab_test',
            },
        ),
        migrations.CreateModel(
            name='AIBatchTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_count', models.IntegerField(default=0, verbose_name='测试次数')),
                ('positive_feedback_count', models.IntegerField(default=0, verbose_name='正面反馈次数')),
                ('negative_feedback_count', models.IntegerField(default=0, verbose_name='负面反馈次数')),
                ('average_rating', models.FloatField(default=0, verbose_name='平均评分')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='转化率')),
                ('cost_per_result', models.FloatField(default=0, verbose_name='每次结果成本')),
                ('metrics', models.JSONField(help_text='如：响应时间、准确率等', verbose_name='其他指标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI A/B测试结果',
                'verbose_name_plural': 'AI A/B测试结果',
                'db_table': 'ai_ab_test_result',
            },
        ),
        migrations.CreateModel(
            name='AIBatchTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：variant_a, variant_b', max_length=50, verbose_name='变体名称')),
                ('description', models.TextField(blank=True, verbose_name='变体描述')),
                ('config_params', models.JSONField(help_text='额外的配置参数', verbose_name='配置参数')),
                ('is_control', models.BooleanField(default=False, verbose_name='是否为对照组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI A/B测试变体',
                'verbose_name_plural': 'AI A/B测试变体',
                'db_table': 'ai_ab_test_variant',
            },
        ),
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI聊天记录',
                'verbose_name_plural': 'AI聊天记录',
                'db_table': 'ai_chat',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI聊天消息',
                'verbose_name_plural': 'AI聊天消息',
                'db_table': 'ai_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('sensitive_word', '敏感词'), ('forbidden_content', '禁止内容'), ('warning_content', '警告内容'), ('required_content', '必填内容')], max_length=20, verbose_name='规则类型')),
                ('content', models.TextField(verbose_name='规则内容')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('severity', models.IntegerField(default=1, help_text='1-5，5最严重', verbose_name='严重程度')),
                ('action', models.CharField(default='block', help_text='block: 阻止, warn: 警告, log: 记录', max_length=50, verbose_name='处理动作')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI合规规则',
                'verbose_name_plural': 'AI合规规则',
                'db_table': 'ai_compliance_rule',
            },
        ),
        migrations.CreateModel(
            name='AIEmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(choices=[('positive', '积极'), ('neutral', '中性'), ('negative', '消极'), ('hesitant', '犹豫'), ('angry', '愤怒'), ('happy', '开心'), ('sad', '悲伤'), ('surprised', '惊讶')], max_length=20, verbose_name='情绪类型')),
                ('keywords', models.JSONField(verbose_name='关键词列表')),
                ('description', models.TextField(blank=True, verbose_name='情绪描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI情绪分析',
                'verbose_name_plural': 'AI情绪分析',
                'db_table': 'ai_emotion_analysis',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('chat_completion', '聊天完成'), ('text_generation', '文本生成'), ('knowledge_retrieval', '知识检索'), ('customer_analysis', '客户分析'), ('meeting_minutes', '会议纪要'), ('project_risk', '项目风险评估'), ('expense_audit', '报销单审核'), ('document_summary', '文档摘要'), ('other', '其他')], default='other', max_length=30, verbose_name='任务类型')),
                ('rating', models.IntegerField(choices=[(1, '非常不满意'), (2, '不满意'), (3, '一般'), (4, '满意'), (5, '非常满意')], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='反馈内容')),
                ('ai_output', models.TextField(verbose_name='AI输出内容')),
                ('input_content', models.TextField(verbose_name='输入内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI效果反馈',
                'verbose_name_plural': 'AI效果反馈',
                'db_table': 'ai_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIIntentRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('inquiry', '询价'), ('comparison', '比价'), ('complaint', '投诉'), ('repurchase', '复购'), ('consultation', '咨询'), ('feedback', '反馈'), ('other', '其他')], max_length=20, verbose_name='意图类型')),
                ('keywords', models.JSONField(verbose_name='关键词列表')),
                ('examples', models.JSONField(verbose_name='示例句子')),
                ('description', models.TextField(blank=True, verbose_name='意图描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI意图识别',
                'verbose_name_plural': 'AI意图识别',
                'db_table': 'ai_intent_recognition',
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, verbose_name='知识库描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI知识库',
                'verbose_name_plural': 'AI知识库',
                'db_table': 'ai_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('file', models.FileField(blank=True, help_text='支持上传PDF、Word、Excel、PPT、TXT等文件', null=True, upload_to='knowledge_files/', verbose_name='附件')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('knowledge_type', models.CharField(choices=[('document', '文档'), ('faq', '常见问题'), ('product', '产品信息'), ('policy', '政策法规'), ('sales', '销售话术'), ('other', '其他')], default='other', max_length=20, verbose_name='知识类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
            ],
            options={
                'verbose_name': 'AI知识库条目',
                'verbose_name_plural': 'AI知识库条目',
                'db_table': 'ai_knowledge_item',
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(verbose_name='向量数据')),
                ('dimension', models.IntegerField(verbose_name='向量维度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI知识库向量',
                'verbose_name_plural': 'AI知识库向量',
                'db_table': 'ai_knowledge_vector',
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('model_call', '模型调用'), ('knowledge_access', '知识库访问'), ('workflow_execution', '工作流执行'), ('chat_interaction', '聊天交互'), ('compliance_check', '合规检查'), ('intent_recognition', '意图识别'), ('emotion_analysis', '情绪分析'), ('action_trigger', '行动触发')], max_length=20, verbose_name='日志类型')),
                ('content', models.JSONField(verbose_name='日志内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI操作日志',
                'verbose_name_plural': 'AI操作日志',
                'db_table': 'ai_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('baidu', '百度文心一言'), ('alibaba', '阿里通义千问'), ('tencent', '腾讯混元'), ('deepseek', 'DeepSeek'), ('doubao', '字节跳动豆包'), ('local', '本地模型')], max_length=50, verbose_name='提供商')),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('text', '文本生成'), ('embedding', '嵌入模型'), ('image', '图像模型'), ('audio', '音频模型')], max_length=20, verbose_name='模型类型')),
                ('model_name', models.CharField(default='', max_length=100, verbose_name='模型标识')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API密钥')),
                ('api_base', models.URLField(blank=True, null=True, verbose_name='API基础URL')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='组织ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目ID')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='0-2，值越高越随机', verbose_name='温度')),
                ('top_p', models.FloatField(default=1.0, help_text='0-1，核采样参数', verbose_name='top_p')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'db_table': 'ai_model_config',
            },
        ),
        migrations.CreateModel(
            name='AISalesStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('strategy_type', models.CharField(choices=[('spin', 'SPIN销售法'), ('fabe', 'FABE销售法'), ('solution', '解决方案销售'), ('challenger', '挑战者销售法'), ('other', '其他')], max_length=20, verbose_name='策略类型')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('config', models.JSONField(verbose_name='策略配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI销售策略',
                'verbose_name_plural': 'AI销售策略',
                'db_table': 'ai_sales_strategy',
            },
        ),
        migrations.CreateModel(
            name='AIWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='工作流描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI工作流',
                'verbose_name_plural': 'AI工作流',
                'db_table': 'ai_workflow',
            },
        ),
        migrations.CreateModel(
            name='AIWorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('input_data', models.JSONField(blank=True, null=True, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, null=True, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '工作流执行记录',
                'verbose_name_plural': '工作流执行记录',
                'db_table': 'ai_workflow_execution',
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_handle', models.CharField(blank=True, max_length=50, null=True, verbose_name='源节点端口')),
                ('target_handle', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标节点端口')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='连接配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作流连接',
                'verbose_name_plural': '工作流连接',
                'db_table': 'ai_workflow_connection',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('ai_model', 'AI模型'), ('data_input', '数据输入'), ('data_output', '数据输出'), ('condition', '条件判断'), ('loop', '循环'), ('delay', '延迟'), ('webhook', 'Webhook')], max_length=20, verbose_name='节点类型')),
                ('config', models.JSONField(verbose_name='节点配置')),
                ('position_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'ai_workflow_node',
            },
        ),
    ]
