# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aibatchtest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aibatchtestresult',
            name='ab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai.aibatchtest', verbose_name='所属测试'),
        ),
        migrations.AddField(
            model_name='aibatchtestvariant',
            name='ab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ai.aibatchtest', verbose_name='所属测试'),
        ),
        migrations.AddField(
            model_name='aibatchtestresult',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aibatchtestvariant', verbose_name='变体'),
        ),
        migrations.AddField(
            model_name='aichat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aichat', verbose_name='聊天会话'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户'),
        ),
        migrations.AddField(
            model_name='aiknowledgebase',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aiknowledgeitem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aiknowledgeitem',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.aiknowledgebase', verbose_name='所属知识库'),
        ),
        migrations.AddField(
            model_name='aiknowledgevector',
            name='knowledge_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='ai.aiknowledgeitem', verbose_name='关联知识条目'),
        ),
        migrations.AddField(
            model_name='ailog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodelconfig',
            unique_together={('provider', 'model_name', 'model_type')},
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='model_config_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aimodelconfig', verbose_name='使用的模型配置'),
        ),
        migrations.AddField(
            model_name='aibatchtestvariant',
            name='model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aimodelconfig', verbose_name='使用的模型配置'),
        ),
        migrations.AddField(
            model_name='aiworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='aiworkflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiworkflow', verbose_name='工作流'),
        ),
        migrations.AddField(
            model_name='workflowconnection',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ai.aiworkflow', verbose_name='所属工作流'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ai.aiworkflow', verbose_name='所属工作流'),
        ),
        migrations.AddField(
            model_name='workflowconnection',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_connections', to='ai.workflownode', verbose_name='源节点'),
        ),
        migrations.AddField(
            model_name='workflowconnection',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_connections', to='ai.workflownode', verbose_name='目标节点'),
        ),
        migrations.AlterUniqueTogether(
            name='aibatchtestvariant',
            unique_together={('ab_test', 'name')},
        ),
    ]
