# Generated by Django 4.2.27 on 2026-03-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiintentrecognition",
            options={"verbose_name": "AI 意图识别", "verbose_name_plural": "AI 意图识别"},
        ),
        migrations.AlterModelOptions(
            name="ailog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI 操作日志",
                "verbose_name_plural": "AI 操作日志",
            },
        ),
        migrations.AddField(
            model_name="aiintentrecognition",
            name="accuracy_rate",
            field=models.FloatField(
                default=0.0, help_text="意图识别准确率", verbose_name="准确率"
            ),
        ),
        migrations.AddField(
            model_name="aiintentrecognition",
            name="confidence_threshold",
            field=models.FloatField(default=0.65, verbose_name="置信度阈值"),
        ),
        migrations.AddField(
            model_name="aiintentrecognition",
            name="training_count",
            field=models.IntegerField(
                default=0, help_text="用于记录该意图被用于训练的次数", verbose_name="训练次数"
            ),
        ),
        migrations.AlterField(
            model_name="aiintentrecognition",
            name="examples",
            field=models.JSONField(default=list, verbose_name="示例句子"),
        ),
        migrations.AlterField(
            model_name="aiintentrecognition",
            name="intent_type",
            field=models.CharField(
                choices=[
                    ("DATA_QUERY", "数据查询"),
                    ("DATA_CREATE", "数据创建"),
                    ("DATA_UPDATE", "数据修改"),
                    ("KNOWLEDGE_BASE", "知识库查询"),
                    ("AI_CHAT", "AI 对话"),
                    ("inquiry", "询价"),
                    ("comparison", "比价"),
                    ("complaint", "投诉"),
                    ("repurchase", "复购"),
                    ("consultation", "咨询"),
                    ("feedback", "反馈"),
                    ("other", "其他"),
                ],
                max_length=30,
                verbose_name="意图类型",
            ),
        ),
        migrations.AlterField(
            model_name="aiintentrecognition",
            name="keywords",
            field=models.JSONField(default=list, verbose_name="关键词列表"),
        ),
        migrations.AlterField(
            model_name="ailog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP 地址"
            ),
        ),
        migrations.CreateModel(
            name="AIIntentRecognitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="用户查询文本")),
                (
                    "recognized_intent",
                    models.CharField(max_length=30, verbose_name="识别的意图类型"),
                ),
                ("confidence", models.FloatField(verbose_name="置信度")),
                (
                    "actual_intent",
                    models.CharField(
                        blank=True,
                        help_text="用户确认后的实际意图",
                        max_length=30,
                        verbose_name="实际意图类型",
                    ),
                ),
                ("entities", models.JSONField(default=dict, verbose_name="识别到的实体")),
                (
                    "action_taken",
                    models.CharField(
                        help_text="query/create/update/chat 等",
                        max_length=20,
                        verbose_name="采取的操作",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("uncertain", "不确定"),
                            ("confirmed", "已确认"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="识别结果",
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, verbose_name="用户反馈")),
                ("is_correct", models.BooleanField(default=True, verbose_name="是否正确")),
                (
                    "used_for_training",
                    models.BooleanField(default=False, verbose_name="是否用于训练"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 意图识别日志",
                "verbose_name_plural": "AI 意图识别日志",
                "db_table": "ai_intent_recognition_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
