# Generated by Django 4.2.27 on 2026-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_alter_aiintentrecognition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("azure", "Azure OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google Gemini"),
                    ("baidu", "百度文心一言"),
                    ("alibaba", "阿里通义千问"),
                    ("tencent", "腾讯混元"),
                    ("deepseek", "DeepSeek"),
                    ("doubao", "字节跳动豆包"),
                    ("ollama", "Ollama (本地模型)"),
                    ("local", "本地模型"),
                ],
                max_length=50,
                verbose_name="提供商",
            ),
        ),
    ]
