# Generated by Django 4.2.27 on 2026-03-27 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0004_alter_aimodelconfig_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("workflow_started", "工作流开始"),
                            ("workflow_completed", "工作流完成"),
                            ("workflow_failed", "工作流失败"),
                            ("node_completed", "节点完成"),
                            ("condition_met", "条件满足"),
                        ],
                        max_length=30,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(max_length=500, verbose_name="Webhook URL"),
                ),
                (
                    "secret_key",
                    models.CharField(blank=True, max_length=100, verbose_name="密钥"),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "不活跃")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次触发时间"),
                ),
                ("failure_count", models.IntegerField(default=0, verbose_name="失败次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="ai.aiworkflow",
                        verbose_name="关联工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流Webhook",
                "verbose_name_plural": "工作流Webhook",
                "db_table": "ai_workflow_webhook",
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=20, verbose_name="版本号")),
                ("workflow_data", models.JSONField(verbose_name="工作流数据")),
                ("nodes", models.JSONField(verbose_name="节点数据")),
                ("connections", models.JSONField(verbose_name="连接数据")),
                ("change_summary", models.TextField(blank=True, verbose_name="变更摘要")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ai.aiworkflow",
                        verbose_name="关联工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流版本",
                "verbose_name_plural": "工作流版本",
                "db_table": "ai_workflow_version",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("customer_service", "客服场景"),
                            ("document_processing", "文档处理"),
                            ("data_analysis", "数据分析"),
                            ("content_generation", "内容生成"),
                            ("automation", "自动化流程"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="分类",
                    ),
                ),
                ("workflow_data", models.JSONField(verbose_name="工作流数据")),
                ("thumbnail", models.URLField(blank=True, verbose_name="缩略图URL")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流模板",
                "verbose_name_plural": "工作流模板",
                "db_table": "ai_workflow_template",
            },
        ),
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="调度名称")),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("interval", "间隔执行"),
                            ("cron", "Cron表达式"),
                            ("once", "单次执行"),
                        ],
                        max_length=20,
                        verbose_name="频率类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="间隔秒数"),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, default=dict, verbose_name="输入数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("paused", "暂停"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次执行时间"),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间"),
                ),
                (
                    "max_concurrent",
                    models.IntegerField(default=1, verbose_name="最大并发数"),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=300, verbose_name="超时时间"),
                ),
                (
                    "error_notification",
                    models.BooleanField(default=True, verbose_name="错误通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="ai.aiworkflow",
                        verbose_name="关联工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流定时调度",
                "verbose_name_plural": "工作流定时调度",
                "db_table": "ai_workflow_schedule",
            },
        ),
        migrations.CreateModel(
            name="AIWorkflowAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("execute", "执行"),
                            ("debug", "调试"),
                            ("share", "分享"),
                            ("export", "导出"),
                            ("permission_change", "权限变更"),
                            ("api_key_operation", "API密钥操作"),
                            ("login", "登录"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("workflow", "工作流"),
                            ("model_config", "模型配置"),
                            ("knowledge_base", "知识库"),
                            ("api_key", "API密钥"),
                            ("user", "用户"),
                            ("system", "系统"),
                        ],
                        max_length=50,
                        verbose_name="资源类型",
                    ),
                ),
                ("resource_id", models.CharField(max_length=100, verbose_name="资源ID")),
                ("details", models.JSONField(default=dict, verbose_name="详细信息")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI工作流审计日志",
                "verbose_name_plural": "AI工作流审计日志",
                "db_table": "ai_workflow_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_id", models.UUIDField(verbose_name="工作流ID")),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("editor", "编辑者"),
                            ("viewer", "查看者"),
                            ("operator", "操作者"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授权人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流权限",
                "verbose_name_plural": "工作流权限",
                "db_table": "ai_workflow_permission",
                "unique_together": {("workflow_id", "user_id")},
            },
        ),
    ]
