# Generated by Django 5.2.1 on 2026-06-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_simplify_ai_model_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="api_base",
            field=models.URLField(
                help_text="OpenAI兼容的API接口地址，例如 https://api.openai.com/v1",
                max_length=300,
                verbose_name="API接口地址",
            ),
        ),
        migrations.CreateModel(
            name="AIOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(max_length=50, verbose_name="操作类型"),
                ),
                ("resource_type", models.CharField(max_length=50, verbose_name="资源类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "预览"),
                            ("confirmed", "已确认"),
                            ("executed", "已执行"),
                            ("failed", "执行失败"),
                            ("rolled_back", "已回退"),
                        ],
                        default="preview",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "preview_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="预览载荷"),
                ),
                (
                    "confirmed_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="确认载荷"),
                ),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="确认令牌"
                    ),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(default=True, verbose_name="是否需要确认"),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "未请求"),
                            ("pending", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="not_requested",
                        max_length=20,
                        verbose_name="回退状态",
                    ),
                ),
                (
                    "rollback_reason",
                    models.TextField(blank=True, default="", verbose_name="回退原因"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
                ),
                (
                    "rolled_back_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回退时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "ai_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_operations",
                        to="ai.aichatmessage",
                        verbose_name="AI消息",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="ai.aichat",
                        verbose_name="关联会话",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_operations",
                        to="ai.aichatmessage",
                        verbose_name="用户消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI操作",
                "verbose_name_plural": "AI操作",
                "db_table": "ai_operation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIOperationChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1, verbose_name="顺序")),
                ("app_label", models.CharField(max_length=50, verbose_name="应用")),
                ("model_name", models.CharField(max_length=100, verbose_name="模型")),
                ("object_pk", models.CharField(max_length=100, verbose_name="对象主键")),
                (
                    "change_type",
                    models.CharField(
                        choices=[("create", "创建"), ("update", "更新"), ("delete", "删除")],
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="变更前快照"),
                ),
                (
                    "after_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="变更后快照"),
                ),
                (
                    "changed_fields",
                    models.JSONField(blank=True, default=list, verbose_name="变更字段"),
                ),
                (
                    "is_rollback_supported",
                    models.BooleanField(default=True, verbose_name="支持回退"),
                ),
                (
                    "rollback_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="回退元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_sets",
                        to="ai.aioperation",
                        verbose_name="所属操作",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI操作变更集",
                "verbose_name_plural": "AI操作变更集",
                "db_table": "ai_operation_change_set",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AIOperationConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=120, unique=True, verbose_name="确认令牌"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="是否已使用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_ai_operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation",
                        to="ai.aioperation",
                        verbose_name="所属操作",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI操作确认",
                "verbose_name_plural": "AI操作确认",
                "db_table": "ai_operation_confirmation",
            },
        ),
        migrations.CreateModel(
            name="AIOperationRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(blank=True, default=dict, verbose_name="结果摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollbacks",
                        to="ai.aioperation",
                        verbose_name="所属操作",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_ai_rollbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="请求人",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI操作回退记录",
                "verbose_name_plural": "AI操作回退记录",
                "db_table": "ai_operation_rollback",
                "ordering": ["-started_at"],
            },
        ),
    ]
