# Generated by Django 5.2.1 on 2026-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_alter_aimodelconfig_api_base_aioperation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodelconfig",
            name="image_model",
        ),
        migrations.RemoveField(
            model_name="aimodelconfig",
            name="video_model",
        ),
        migrations.AddField(
            model_name="aimodelconfig",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="是否为系统默认使用的模型配置", verbose_name="是否默认"
            ),
        ),
        migrations.AddField(
            model_name="aimodelconfig",
            name="model_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="可用模型标识列表，如 gpt-4o-mini, gpt-4o",
                verbose_name="模型名称列表",
            ),
        ),
    ]
