# Generated by Django 5.2.15 on 2026-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0009_simplify_model_config_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aioperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("preview", "预览"),
                    ("confirmed", "已确认"),
                    ("executed", "已执行"),
                    ("failed", "执行失败"),
                    ("cancelled", "已取消"),
                    ("rolled_back", "已回退"),
                ],
                default="preview",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
