# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "普通"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_broadcast",
                    models.BooleanField(default=False, verbose_name="是否广播消息"),
                ),
                (
                    "target_users",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="目标用户ID列表，JSON格式",
                        verbose_name="目标用户",
                    ),
                ),
                (
                    "target_departments",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="目标部门ID列表，JSON格式",
                        verbose_name="目标部门",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=100, verbose_name="关联对象类型"),
                ),
                (
                    "related_object_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(blank=True, max_length=500, verbose_name="跳转链接"),
                ),
                (
                    "expire_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="分类代码"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("announcement", "公告通知"),
                            ("approval", "审批通知"),
                            ("task", "任务通知"),
                            ("system", "系统通知"),
                            ("comment", "评论回复通知"),
                        ],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="layui-icon-notice", max_length=50, verbose_name="图标"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "消息分类",
                "verbose_name_plural": "消息分类",
                "db_table": "message_category",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MessageUserRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                ("is_starred", models.BooleanField(default=False, verbose_name="是否标星")),
                (
                    "read_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户消息关系",
                "verbose_name_plural": "用户消息关系",
                "db_table": "message_user_relation",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_email",
                    models.BooleanField(default=True, verbose_name="启用邮件通知"),
                ),
                (
                    "enable_browser",
                    models.BooleanField(default=True, verbose_name="启用浏览器通知"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰开始时间"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰结束时间"),
                ),
                (
                    "notify_announcement",
                    models.BooleanField(default=True, verbose_name="公告通知"),
                ),
                (
                    "notify_approval",
                    models.BooleanField(default=True, verbose_name="审批通知"),
                ),
                ("notify_task", models.BooleanField(default=True, verbose_name="任务通知")),
                (
                    "notify_comment",
                    models.BooleanField(default=True, verbose_name="评论通知"),
                ),
                (
                    "notify_system",
                    models.BooleanField(default=True, verbose_name="系统通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户通知偏好",
                "verbose_name_plural": "用户通知偏好",
                "db_table": "notification_preference",
            },
        ),
    ]
