# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("message", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="messageuserrelation",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_relations",
                to="message.message",
                verbose_name="消息",
            ),
        ),
        migrations.AddField(
            model_name="messageuserrelation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_relations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.messagecategory",
                verbose_name="消息分类",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddIndex(
            model_name="messageuserrelation",
            index=models.Index(
                fields=["user", "is_read"], name="message_use_user_id_eb0665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageuserrelation",
            index=models.Index(
                fields=["user", "is_starred"], name="message_use_user_id_38d1b0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messageuserrelation",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="message_created_19da1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_active"],
                name="message_is_acti_11f079_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="message_related_515fb1_idx",
            ),
        ),
    ]
