# Generated by Django 4.2.27 on 2026-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="ai_suggested_replies",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="AI建议回复"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_summary",
            field=models.TextField(blank=True, null=True, verbose_name="AI消息摘要"),
        ),
    ]
