# Generated by Django 5.2.1 on 2026-06-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_message_ai_suggested_replies_message_ai_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_message_center", "查看消息中心"),
                    ("create_message", "发送消息"),
                    ("mark_message_read", "标记已读"),
                    ("star_message", "标星消息"),
                    ("batch_message_operation", "批量操作"),
                    ("view_message_preference", "查看通知偏好"),
                    ("change_message_preference", "编辑通知偏好"),
                    ("view_message_stats", "查看消息统计"),
                ],
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
            },
        ),
    ]
