# Generated by Django 5.2.1 on 2026-06-22 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_options'),
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('direct', '单聊'), ('group', '群聊'), ('department', '部门群'), ('system', '系统通知')], db_index=True, max_length=20, verbose_name='会话类型')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='会话名称')),
                ('direct_key', models.CharField(blank=True, help_text='排序后的两个用户ID组成的稳定键', max_length=120, null=True, unique=True, verbose_name='单聊唯一键')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后消息时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
            ],
            options={
                'verbose_name': '沟通会话',
                'verbose_name_plural': '沟通会话',
                'db_table': 'message_conversation',
                'ordering': ['-last_message_at', '-created_at'],
                'permissions': [('view_conversation_center', '查看沟通中心'), ('start_direct_conversation', '发起单聊'), ('create_group_conversation', '创建群聊'), ('manage_group_conversation', '管理群聊'), ('send_conversation_message', '发送沟通消息'), ('convert_message_to_task', '消息转任务'), ('view_message_read_receipts', '查看消息已读回执')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=20, verbose_name='成员角色')),
                ('is_muted', models.BooleanField(default=False, verbose_name='是否免打扰')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后已读时间')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_relations', to='message.conversation', verbose_name='会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '会话成员',
                'verbose_name_plural': '会话成员',
                'db_table': 'message_conversation_member',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(related_name='conversations', through='message.ConversationMember', to=settings.AUTH_USER_MODEL, verbose_name='会话成员'),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('system', '系统'), ('task', '任务')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.conversation', verbose_name='会话')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='message.conversationmessage', verbose_name='引用消息')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '会话消息',
                'verbose_name_plural': '会话消息',
                'db_table': 'message_conversation_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message.conversationmessage', verbose_name='最后已读消息'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message.conversationmessage', verbose_name='最后一条消息'),
        ),
        migrations.CreateModel(
            name='ConversationMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('delivered', '已送达'), ('read', '已读')], default='delivered', max_length=20, verbose_name='回执状态')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='送达时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='message.conversationmessage', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_message_receipts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息回执',
                'verbose_name_plural': '消息回执',
                'db_table': 'message_conversation_receipt',
            },
        ),
        migrations.CreateModel(
            name='ConversationTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversation_task_links', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='message.conversationmessage', verbose_name='来源消息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_links', to='project.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '消息转任务关联',
                'verbose_name_plural': '消息转任务关联',
                'db_table': 'message_conversation_task_link',
            },
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='message_con_convers_1ce924_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['sender', 'created_at'], name='message_con_sender__b15d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['message_type'], name='message_con_message_dcef2c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'left_at'], name='message_con_user_id_a498e8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'left_at'], name='message_con_convers_536bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'role'], name='message_con_convers_c28ec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmember',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='message_con_convers_279302_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='message_con_last_me_265c99_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessagereceipt',
            index=models.Index(fields=['user', 'status'], name='message_con_user_id_ecd8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessagereceipt',
            index=models.Index(fields=['message', 'status'], name='message_con_message_791048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmessagereceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversationtasklink',
            index=models.Index(fields=['message'], name='message_con_message_a1315f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationtasklink',
            index=models.Index(fields=['task'], name='message_con_task_id_10ec88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationtasklink',
            unique_together={('message', 'task')},
        ),
    ]
