# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="电话号码")),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="客户名称"
                    ),
                ),
                (
                    "call_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="拨号时间"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="通话时长(秒)")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未接通"), (1, "已通话"), (2, "呼叫失败"), (3, "通话中")],
                        default=0,
                        verbose_name="通话状态",
                    ),
                ),
                ("call_count", models.IntegerField(default=0, verbose_name="拨通次数")),
                (
                    "flow_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="通话流水号"
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "拨号记录",
                "verbose_name_plural": "拨号记录",
                "ordering": ["-call_time"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人姓名"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否主要联系人"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="职位"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮箱"
                    ),
                ),
            ],
            options={
                "verbose_name": "客户联系人",
                "verbose_name_plural": "客户联系人",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="客户名称"
                    ),
                ),
                (
                    "grade_id",
                    models.PositiveIntegerField(default=0, verbose_name="客户等级ID"),
                ),
                (
                    "industry_id",
                    models.PositiveIntegerField(default=0, verbose_name="所属行业ID"),
                ),
                (
                    "services_id",
                    models.PositiveIntegerField(default=0, verbose_name="客户意向ID"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="城市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="区/县"
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="乡镇/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="详细地址"
                    ),
                ),
                (
                    "intent_status",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="意向状态"
                    ),
                ),
                (
                    "admin_id",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="录入人ID"
                    ),
                ),
                (
                    "belong_uid",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="所属人ID"
                    ),
                ),
                (
                    "belong_did",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="所属部门ID"
                    ),
                ),
                (
                    "belong_time",
                    models.PositiveBigIntegerField(
                        blank=True, default=0, verbose_name="获取时间"
                    ),
                ),
                (
                    "distribute_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="最新分配时间"),
                ),
                (
                    "follow_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="最新跟进时间"),
                ),
                (
                    "next_time",
                    models.PositiveBigIntegerField(
                        blank=True, default=0, verbose_name="下次跟进时间"
                    ),
                ),
                (
                    "discard_time",
                    models.BigIntegerField(blank=True, default=0, verbose_name="废弃时间"),
                ),
                (
                    "share_ids",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="共享人员ID"
                    ),
                ),
                (
                    "file_ids",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="附件ids"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="客户描述")),
                ("market", models.TextField(blank=True, verbose_name="主要经营业务")),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "tax_bank",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="开户银行"
                    ),
                ),
                (
                    "tax_banksn",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="银行账号"
                    ),
                ),
                (
                    "tax_num",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="纳税人识别号"
                    ),
                ),
                (
                    "tax_mobile",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="税务联系电话"
                    ),
                ),
                (
                    "tax_address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="税务地址"
                    ),
                ),
                ("is_lock", models.BooleanField(default=False, verbose_name="锁定状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户表",
                "verbose_name_plural": "客户表",
                "db_table": "mimu_customer",
            },
        ),
        migrations.CreateModel(
            name="CustomerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, unique=True, verbose_name="合同编号"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="合同名称")),
                ("category_id", models.IntegerField(default=0, verbose_name="分类id")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="合同金额"
                    ),
                ),
                ("sign_date", models.DateField(verbose_name="签订日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("signed", "已签订"),
                            ("executing", "执行中"),
                            ("completed", "已完成"),
                            ("terminated", "已终止"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="合同状态",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sales", "销售合同"),
                            ("service", "服务合同"),
                            ("maintenance", "维护合同"),
                            ("consulting", "咨询合同"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="合同类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="合同描述")),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "客户合同",
                "verbose_name_plural": "客户合同",
                "db_table": "mimu_customer_contract",
                "ordering": ["-sign_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True, verbose_name="字段值")),
            ],
            options={
                "verbose_name": "客户自定义字段值",
                "verbose_name_plural": "客户自定义字段值",
                "db_table": "mimu_customer_custom_field_value",
            },
        ),
        migrations.CreateModel(
            name="CustomerField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="字段名称")),
                (
                    "field_name",
                    models.CharField(max_length=50, unique=True, verbose_name="字段标识"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "单行文本"),
                            ("number", "数字"),
                            ("date", "日期"),
                            ("datetime", "日期时间"),
                            ("textarea", "多行文本"),
                            ("select", "下拉选择"),
                            ("checkbox", "复选框"),
                            ("radio", "单选框"),
                        ],
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "options",
                    models.TextField(blank=True, null=True, verbose_name="选项配置"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                ("is_unique", models.BooleanField(default=False, verbose_name="是否唯一")),
                (
                    "is_list_display",
                    models.BooleanField(default=False, verbose_name="是否列表显示"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户自定义字段",
                "verbose_name_plural": "客户自定义字段",
                "db_table": "mimu_customer_field",
            },
        ),
        migrations.CreateModel(
            name="CustomerGrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="客户等级名称"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "status",
                    models.PositiveSmallIntegerField(default=1, verbose_name="状态"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户等级",
                "verbose_name_plural": "客户等级",
                "db_table": "mimu_customer_grade",
            },
        ),
        migrations.CreateModel(
            name="CustomerIntent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="意向名称"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "status",
                    models.PositiveSmallIntegerField(default=1, verbose_name="状态"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户意向",
                "verbose_name_plural": "客户意向",
                "db_table": "mimu_customer_intent",
            },
        ),
        migrations.CreateModel(
            name="CustomerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, unique=True, verbose_name="发票编号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="发票金额"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=13.0, max_digits=5, verbose_name="税率"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="税额"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="开票日期")),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("ordinary", "普通发票"),
                            ("special", "专用发票"),
                            ("electronic", "电子发票"),
                        ],
                        default="ordinary",
                        max_length=20,
                        verbose_name="发票类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("issued", "已开票"),
                            ("sent", "已发送"),
                            ("received", "已收到"),
                            ("paid", "已付款"),
                            ("cancelled", "已作废"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="发票状态",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100, verbose_name="关联合同编号"),
                ),
                ("content", models.TextField(blank=True, verbose_name="发票内容")),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "客户发票",
                "verbose_name_plural": "客户发票",
                "db_table": "mimu_customer_invoice",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="订单编号"),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="产品名称")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="订单金额"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认"),
                            ("processing", "处理中"),
                            ("shipped", "已发货"),
                            ("delivered", "已交付"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="订单描述")),
                ("remark", models.TextField(blank=True, verbose_name="备注信息")),
                (
                    "finance_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("synced", "已同步"),
                            ("invoiced", "已开票"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="财务状态",
                    ),
                ),
                (
                    "invoice_request_status",
                    models.CharField(
                        choices=[
                            ("none", "未申请"),
                            ("requested", "已申请"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="开票申请状态",
                    ),
                ),
                (
                    "invoice_request_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开票申请时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
                (
                    "auto_generated",
                    models.BooleanField(default=False, verbose_name="是否自动生成"),
                ),
            ],
            options={
                "verbose_name": "客户订单",
                "verbose_name_plural": "客户订单",
                "db_table": "mimu_customer_order",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerOrderCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True, verbose_name="字段值")),
            ],
            options={
                "verbose_name": "订单自定义字段值",
                "verbose_name_plural": "订单自定义字段值",
                "db_table": "mimu_customer_order_custom_field_value",
            },
        ),
        migrations.CreateModel(
            name="CustomerSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="客户渠道名称"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "status",
                    models.PositiveSmallIntegerField(default=1, verbose_name="状态"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户来源",
                "verbose_name_plural": "客户来源",
                "db_table": "mimu_customer_source",
            },
        ),
        migrations.CreateModel(
            name="FollowField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="字段名称")),
                ("field_name", models.CharField(max_length=50, verbose_name="字段标识")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("number", "数字"),
                            ("date", "日期"),
                            ("datetime", "日期时间"),
                            ("select", "下拉选择"),
                            ("textarea", "多行文本"),
                            ("checkbox", "复选框"),
                            ("radio", "单选框"),
                            ("file", "文件上传"),
                        ],
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                ("options", models.TextField(blank=True, verbose_name="选项值")),
                ("is_required", models.BooleanField(default=True, verbose_name="是否必填")),
                (
                    "is_list_display",
                    models.BooleanField(default=True, verbose_name="是否列表显示"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "跟进字段",
                "verbose_name_plural": "跟进字段",
                "db_table": "basedata_follow_field",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FollowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_type",
                    models.CharField(
                        choices=[
                            ("phone", "电话沟通"),
                            ("visit", "上门拜访"),
                            ("email", "邮件联系"),
                            ("meeting", "会议洽谈"),
                            ("other", "其他"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="跟进类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="跟进内容")),
                (
                    "follow_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="跟进时间"),
                ),
                (
                    "next_follow_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次跟进时间"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "客户跟进记录",
                "verbose_name_plural": "客户跟进记录",
                "db_table": "mimu_customer_follow_record",
                "ordering": ["-follow_time"],
            },
        ),
        migrations.CreateModel(
            name="FollowRecordCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True, verbose_name="字段值")),
            ],
            options={
                "verbose_name": "跟进记录自定义字段值",
                "verbose_name_plural": "跟进记录自定义字段值",
                "db_table": "mimu_follow_record_custom_field_value",
            },
        ),
        migrations.CreateModel(
            name="OrderField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="字段名称")),
                ("field_name", models.CharField(max_length=50, verbose_name="字段标识")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("number", "数字"),
                            ("decimal", "小数"),
                            ("date", "日期"),
                            ("datetime", "日期时间"),
                            ("select", "下拉选择"),
                            ("textarea", "多行文本"),
                            ("checkbox", "复选框"),
                            ("radio", "单选框"),
                        ],
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                ("options", models.TextField(blank=True, verbose_name="选项值")),
                ("is_required", models.BooleanField(default=True, verbose_name="是否必填")),
                (
                    "is_summary",
                    models.BooleanField(default=False, verbose_name="是否统计字段"),
                ),
                (
                    "is_list_display",
                    models.BooleanField(default=True, verbose_name="是否列表显示"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "订单字段",
                "verbose_name_plural": "订单字段",
                "db_table": "basedata_order_field",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SpiderTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255, verbose_name="任务名称")),
                ("spider_keywords", models.TextField(verbose_name="爬虫关键词")),
                (
                    "data_region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="数据地区限制"
                    ),
                ),
                (
                    "industry_limit",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="行业限制"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="省份地区"
                    ),
                ),
                (
                    "insured_count",
                    models.CharField(
                        choices=[
                            ("不限", "不限"),
                            ("0", "0"),
                            ("1-49", "1-49"),
                            ("50-99", "50-99"),
                            ("100-999", "100-999"),
                            ("1000-4999", "1000-4999"),
                            ("5000以上", "5000以上"),
                        ],
                        max_length=20,
                        verbose_name="参保人数",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        choices=[
                            ("不限", "不限"),
                            ("有有效手机号", "有有效手机号"),
                            ("有固定电话", "有固定电话"),
                            ("有400/800电话", "有400/800电话"),
                        ],
                        max_length=50,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "运行中"), (2, "停止")], default=2, verbose_name="状态"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "delete_time",
                    models.PositiveBigIntegerField(default=0, verbose_name="删除时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
            },
        ),
    ]
