# Generated by Django 4.2.27 on 2026-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ai_intent_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="从沟通记录中自动提取的标签",
                verbose_name="AI意向标签",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_next_followup_suggestion",
            field=models.TextField(blank=True, null=True, verbose_name="AI跟进建议"),
        ),
        migrations.AddField(
            model_name="customer",
            name="ai_score",
            field=models.FloatField(
                default=0.0, help_text="AI预测的成单概率0-100", verbose_name="AI客户意向评分"
            ),
        ),
        migrations.AddField(
            model_name="followrecord",
            name="ai_key_points",
            field=models.JSONField(blank=True, default=list, verbose_name="提取的关键点"),
        ),
        migrations.AddField(
            model_name="followrecord",
            name="ai_sentiment",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="客户情绪分析"
            ),
        ),
        migrations.AddField(
            model_name="followrecord",
            name="ai_summary",
            field=models.TextField(blank=True, null=True, verbose_name="AI自动总结"),
        ),
    ]
