# Generated by Django 5.2.15 on 2026-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_customerfield_formula_expression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerfield",
            name="relation_type",
            field=models.CharField(
                choices=[("bind", "关联绑定"), ("copy", "同步赋值"), ("calculate", "计算结果")],
                default="bind",
                max_length=20,
                verbose_name="关联方式",
            ),
        ),
    ]
