# Generated by Django 5.2.1 on 2026-07-04 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contract", "0009_add_review_type_to_contract_ai_review"),
        ("inventory", "0002_initial"),
        ("production", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PRReviewRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="规则编码"),
                ),
                (
                    "scenario",
                    models.CharField(blank=True, max_length=50, verbose_name="适用场景"),
                ),
                (
                    "condition_json",
                    models.JSONField(blank=True, default=dict, verbose_name="条件配置"),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("filter", "自动过滤"),
                            ("manual_review", "人工复核"),
                            ("approve", "进入审批"),
                            ("urgent_approve", "紧急审批"),
                        ],
                        default="manual_review",
                        max_length=20,
                        verbose_name="建议动作",
                    ),
                ),
                ("priority", models.IntegerField(default=100, verbose_name="优先级")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "PR审核规则",
                "verbose_name_plural": "PR审核规则",
                "db_table": "supply_chain_pr_review_rule",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="DemandForecastPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="预测计划名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="预测计划编号"),
                ),
                ("period_start", models.DateField(verbose_name="周期开始日期")),
                ("period_end", models.DateField(verbose_name="周期结束日期")),
                (
                    "version",
                    models.CharField(default="1.0", max_length=20, verbose_name="版本"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("running", "计算中"),
                            ("generated", "已生成"),
                            ("reviewing", "评审中"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="预测摘要")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_demand_forecast_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.product",
                        verbose_name="关联产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求预测计划",
                "verbose_name_plural": "需求预测计划",
                "db_table": "supply_chain_demand_forecast_plan",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="DemandForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="预测量"
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="安全库存"
                    ),
                ),
                (
                    "recommended_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="建议备料量"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="置信度"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="风险等级"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "forecast_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="supply_chain.demandforecastplan",
                        verbose_name="预测计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求预测结果",
                "verbose_name_plural": "需求预测结果",
                "db_table": "supply_chain_demand_forecast_result",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="DemandForecastSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipped_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="历史出货量"
                    ),
                ),
                (
                    "inventory_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="当前库存"
                    ),
                ),
                (
                    "wip_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="在制数量"
                    ),
                ),
                (
                    "inbound_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="在途数量"
                    ),
                ),
                (
                    "prepared_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="已备料数量"
                    ),
                ),
                (
                    "manual_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="人工修正量"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "forecast_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="supply_chain.demandforecastplan",
                        verbose_name="预测计划",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.product",
                        verbose_name="关联产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求预测快照",
                "verbose_name_plural": "需求预测快照",
                "db_table": "supply_chain_demand_forecast_snapshot",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="MaterialPreparationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="评审单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待评审"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="评审意见")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "forecast_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="supply_chain.demandforecastresult",
                        verbose_name="预测结果",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_preparation_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评审人",
                    ),
                ),
            ],
            options={
                "verbose_name": "备料评审",
                "verbose_name_plural": "备料评审",
                "db_table": "supply_chain_material_preparation_review",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OutsourceIssueOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="委外发料单号"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="委外数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("checking", "齐套校验中"),
                            ("shortage", "缺料"),
                            ("ready", "齐套完成"),
                            ("picking", "备料中"),
                            ("issued", "已发料"),
                            ("notified", "已通知"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_outsource_issue_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "production_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outsource_issue_orders",
                        to="production.productionplan",
                        verbose_name="生产计划",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "委外发料单",
                "verbose_name_plural": "委外发料单",
                "db_table": "supply_chain_outsource_issue_order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OutsourceIssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=100, verbose_name="物料名称"),
                ),
                (
                    "material_code",
                    models.CharField(blank=True, max_length=50, verbose_name="物料编码"),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=100, verbose_name="规格型号"),
                ),
                (
                    "required_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="应发数量"
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="可用数量"
                    ),
                ),
                (
                    "issued_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="已发数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待校验"),
                            ("ready", "齐套"),
                            ("shortage", "缺料"),
                            ("spec_mismatch", "规格不符"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "bom_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.bomitem",
                        verbose_name="BOM明细",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                        verbose_name="库存物料",
                    ),
                ),
                (
                    "issue_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="supply_chain.outsourceissueorder",
                        verbose_name="委外发料单",
                    ),
                ),
            ],
            options={
                "verbose_name": "委外发料明细",
                "verbose_name_plural": "委外发料明细",
                "db_table": "supply_chain_outsource_issue_item",
            },
        ),
        migrations.CreateModel(
            name="OutsourceIssueStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=20, verbose_name="原状态"),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="新状态")),
                (
                    "message",
                    models.CharField(blank=True, max_length=255, verbose_name="说明"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "issue_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="supply_chain.outsourceissueorder",
                        verbose_name="委外发料单",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "委外发料状态日志",
                "verbose_name_plural": "委外发料状态日志",
                "db_table": "supply_chain_outsource_issue_status_log",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PriceReviewOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="复核单号"),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=14, verbose_name="报价单价"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("parsing", "解析中"),
                            ("breakdown", "拆解中"),
                            ("reviewing", "复核中"),
                            ("exception", "异常待处理"),
                            ("approved", "已通过"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("ai_summary", models.TextField(blank=True, verbose_name="AI摘要")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_price_review_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                        verbose_name="物料",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_reviews",
                        to="inventory.purchaseorder",
                        verbose_name="采购订单",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "单价复核单",
                "verbose_name_plural": "单价复核单",
                "db_table": "supply_chain_price_review_order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PriceReviewDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="文件路径"),
                ),
                ("raw_text", models.TextField(blank=True, verbose_name="OCR文本")),
                (
                    "parsed_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="结构化结果"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "review_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="supply_chain.pricerevieworder",
                        verbose_name="复核单",
                    ),
                ),
            ],
            options={
                "verbose_name": "单价复核文档",
                "verbose_name_plural": "单价复核文档",
                "db_table": "supply_chain_price_review_document",
            },
        ),
        migrations.CreateModel(
            name="PriceReviewConclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="结论"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="风险等级"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "abnormal_items",
                    models.JSONField(blank=True, default=list, verbose_name="异常项"),
                ),
                (
                    "negotiation_points",
                    models.JSONField(blank=True, default=list, verbose_name="议价点"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="复核人",
                    ),
                ),
                (
                    "review_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion",
                        to="supply_chain.pricerevieworder",
                        verbose_name="复核单",
                    ),
                ),
            ],
            options={
                "verbose_name": "单价复核结论",
                "verbose_name_plural": "单价复核结论",
                "db_table": "supply_chain_price_review_conclusion",
            },
        ),
        migrations.CreateModel(
            name="PriceReviewComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(max_length=50, verbose_name="成本项类型"),
                ),
                (
                    "component_name",
                    models.CharField(max_length=100, verbose_name="成本项名称"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=14, verbose_name="金额"
                    ),
                ),
                (
                    "reference_amount",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=14, verbose_name="参考金额"
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="是否异常"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "review_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="supply_chain.pricerevieworder",
                        verbose_name="复核单",
                    ),
                ),
            ],
            options={
                "verbose_name": "单价复核拆解项",
                "verbose_name_plural": "单价复核拆解项",
                "db_table": "supply_chain_price_review_component",
            },
        ),
        migrations.CreateModel(
            name="PRReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="审核任务编号"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=50, verbose_name="来源类型"),
                ),
                (
                    "source_code",
                    models.CharField(blank=True, max_length=50, verbose_name="来源单号"),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="是否异常"),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="建议动作"
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(blank=True, default=dict, verbose_name="审核依据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待识别"),
                            ("rule_matched", "规则命中"),
                            ("auto_approved", "自动通过"),
                            ("manual_review", "人工复核"),
                            ("done", "已处理"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pr_review_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "matched_rules",
                    models.ManyToManyField(
                        blank=True, to="supply_chain.prreviewrule", verbose_name="命中规则"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_pr_review_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="复核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "PR审核任务",
                "verbose_name_plural": "PR审核任务",
                "db_table": "supply_chain_pr_review_task",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="PRReviewEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="依据标签")),
                (
                    "value",
                    models.CharField(blank=True, max_length=255, verbose_name="依据值"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply_chain.prreviewrule",
                        verbose_name="规则",
                    ),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="supply_chain.prreviewtask",
                        verbose_name="审核任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "PR审核依据",
                "verbose_name_plural": "PR审核依据",
                "db_table": "supply_chain_pr_review_evidence",
            },
        ),
        migrations.CreateModel(
            name="SampleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="打样编号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                (
                    "specification",
                    models.CharField(blank=True, max_length=100, verbose_name="规格型号"),
                ),
                ("required_date", models.DateField(verbose_name="要求交期")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=14, verbose_name="打样数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("ordered", "已下单"),
                            ("received", "已到货"),
                            ("pickup_pending", "待领样"),
                            ("picked_up", "已领样"),
                            ("closed", "已关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineering_sample_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="研发工程师",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_samples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contract.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "打样申请",
                "verbose_name_plural": "打样申请",
                "db_table": "supply_chain_sample_request",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SampleReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="到货数量"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="到货时间"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="领样地点"),
                ),
                (
                    "photo_path",
                    models.CharField(blank=True, max_length=500, verbose_name="照片路径"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_samples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登记人",
                    ),
                ),
                (
                    "sample_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="supply_chain.samplerequest",
                        verbose_name="打样申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "样品到货",
                "verbose_name_plural": "样品到货",
                "db_table": "supply_chain_sample_receipt",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SamplePickupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="领样时间"),
                ),
                ("is_overdue", models.BooleanField(default=False, verbose_name="是否超时")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picked_samples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="领样人",
                    ),
                ),
                (
                    "sample_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_records",
                        to="supply_chain.samplerequest",
                        verbose_name="打样申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "样品领样记录",
                "verbose_name_plural": "样品领样记录",
                "db_table": "supply_chain_sample_pickup_record",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50, verbose_name="事件类型")),
                ("title", models.CharField(max_length=200, verbose_name="事件标题")),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=50, verbose_name="对象类型"),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="对象ID"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="事件载荷"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应链事件日志",
                "verbose_name_plural": "供应链事件日志",
                "db_table": "supply_chain_event_log",
                "ordering": ["-create_time"],
            },
        ),
    ]
