# Generated by Django 5.2.1 on 2026-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplereceipt",
            name="pickup_reminded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="上次提醒时间"),
        ),
        migrations.AddField(
            model_name="samplereceipt",
            name="reminder_count",
            field=models.IntegerField(default=0, verbose_name="提醒次数"),
        ),
    ]
