# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="会议主题")),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("regular", "例会"),
                            ("project", "项目会议"),
                            ("training", "培训会议"),
                            ("review", "评审会议"),
                            ("emergency", "紧急会议"),
                            ("other", "其他"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="会议类型",
                    ),
                ),
                ("meeting_date", models.DateTimeField(verbose_name="会议时间")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="会议地点"),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="主持人"),
                ),
                ("attendees", models.TextField(blank=True, verbose_name="参会人员")),
                ("content", models.TextField(blank=True, verbose_name="会议内容")),
                ("decisions", models.TextField(blank=True, verbose_name="会议决议")),
                ("action_items", models.TextField(blank=True, verbose_name="行动项")),
                ("attachments", models.TextField(blank=True, verbose_name="附件")),
                ("is_public", models.BooleanField(
                    default=True, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会议纪要",
                "verbose_name_plural": "会议纪要",
                "db_table": "personal_meeting_minutes",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="PersonalContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="公司"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="职位"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="手机"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="标签"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="重要联系人"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人通讯录",
                "verbose_name_plural": "个人通讯录",
                "db_table": "personal_contact",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PersonalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="笔记标题")),
                ("content", models.TextField(verbose_name="笔记内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("work", "工作笔记"),
                            ("study", "学习笔记"),
                            ("meeting", "会议纪要"),
                            ("idea", "想法记录"),
                            ("other", "其他"),
                        ],
                        default="work",
                        max_length=20,
                        verbose_name="笔记分类",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="标签"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="重要标记"),
                ),
                ("is_private", models.BooleanField(
                    default=True, verbose_name="私人笔记")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人笔记",
                "verbose_name_plural": "个人笔记",
                "db_table": "personal_note",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="日程标题")),
                ("content", models.TextField(blank=True, verbose_name="日程内容")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="地点"),
                ),
                (
                    "reminder_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提醒时间"),
                ),
                ("is_all_day", models.BooleanField(
                    default=False, verbose_name="全天事件")),
                ("is_private", models.BooleanField(
                    default=False, verbose_name="私人事件")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人日程",
                "verbose_name_plural": "个人日程",
                "db_table": "personal_schedule",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="PersonalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待办"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"),
                ),
                ("progress", models.IntegerField(
                    default=0, verbose_name="完成进度(%)")),
                (
                    "estimated_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="预估工时"),
                ),
                (
                    "actual_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="实际工时"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人任务",
                "verbose_name_plural": "个人任务",
                "db_table": "personal_task",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="工作标题")),
                ("content", models.TextField(verbose_name="工作内容")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("daily", "日常工作"),
                            ("project", "项目工作"),
                            ("meeting", "会议"),
                            ("training", "培训学习"),
                            ("other", "其他"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="工作类型",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="工作日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("duration", models.FloatField(verbose_name="工作时长(小时)")),
                ("progress", models.IntegerField(
                    default=0, verbose_name="完成进度(%)")),
                (
                    "difficulty",
                    models.IntegerField(default=3, verbose_name="难度系数(1-5)"),
                ),
                ("result", models.TextField(blank=True, verbose_name="工作成果")),
                ("problem", models.TextField(blank=True, verbose_name="遇到问题")),
                ("next_plan", models.TextField(blank=True, verbose_name="下步计划")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "工作记录",
                "verbose_name_plural": "工作记录",
                "db_table": "personal_work_record",
                "ordering": ["-work_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="汇报标题")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "日报"),
                            ("weekly", "周报"),
                            ("monthly", "月报"),
                            ("project", "项目汇报"),
                            ("special", "专项汇报"),
                        ],
                        max_length=20,
                        verbose_name="汇报类型",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="汇报日期")),
                ("summary", models.TextField(verbose_name="工作总结")),
                ("completed_work", models.TextField(verbose_name="已完成工作")),
                ("next_work", models.TextField(verbose_name="下期工作计划")),
                ("problems", models.TextField(blank=True, verbose_name="存在问题")),
                ("suggestions", models.TextField(blank=True, verbose_name="意见建议")),
                ("attachments", models.TextField(blank=True, verbose_name="附件列表")),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="已提交"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.department",
                        verbose_name="部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作汇报",
                "verbose_name_plural": "工作汇报",
                "db_table": "personal_work_report",
                "ordering": ["-report_date"],
            },
        ),
    ]
