# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oa", "0002_initial"),
        ("personal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("department", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workreport",
            name="recipient_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="received_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收人",
            ),
        ),
        migrations.AddField(
            model_name="workreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="汇报人",
            ),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.department",
                verbose_name="部门",
            ),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="personaltask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="personalschedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="personalnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="personalcontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="meetingminutes",
            name="meeting_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="oa.meetingrecord",
                verbose_name="关联会议记录",
            ),
        ),
        migrations.AddField(
            model_name="meetingminutes",
            name="recorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recorded_meeting_minutes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="记录人",
            ),
        ),
        migrations.AddField(
            model_name="meetingminutes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
    ]
