# Generated by Django 5.2.1 on 2026-06-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonalSchedule",
        ),
    ]
