# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="企业名称"),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=60, verbose_name="所在城市"),
                ),
                (
                    "bank",
                    models.CharField(default="", max_length=60, verbose_name="开户银行"),
                ),
                (
                    "bank_sn",
                    models.CharField(default="", max_length=60, verbose_name="银行帐号"),
                ),
                (
                    "tax_num",
                    models.CharField(default="", max_length=100, verbose_name="纳税人识别号"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=20, verbose_name="开票电话"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=200, verbose_name="开票地址"),
                ),
                (
                    "remark",
                    models.CharField(default="", max_length=500, verbose_name="备注说明"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        db_column="status",
                        default=1,
                        help_text="状态：-1删除 0禁用 1启用",
                        verbose_name="状态",
                    ),
                ),
                ("create_time", models.BigIntegerField(default=0, verbose_name="创建时间")),
                ("update_time", models.BigIntegerField(default=0, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "企业信息",
                "verbose_name_plural": "企业信息",
                "db_table": "mimu_enterprise",
            },
        ),
    ]
