# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.IntegerField(
                    default=0, verbose_name="审批内容ID")),
                (
                    "check_type",
                    models.SmallIntegerField(
                        choices=[(1, "自由审批"), (2, "固定审批")],
                        default=1,
                        verbose_name="审批类型",
                    ),
                ),
                (
                    "check_table",
                    models.CharField(
                        default="审批数据表", max_length=255, verbose_name="审批数据表"
                    ),
                ),
                ("flow_id", models.IntegerField(default=0, verbose_name="审批流程ID")),
                ("step_id", models.IntegerField(default=0, verbose_name="审批步骤ID")),
                ("check_uid", models.IntegerField(default=0, verbose_name="审批人ID")),
                ("check_time", models.BigIntegerField(
                    default=0, verbose_name="审批时间")),
                (
                    "check_status",
                    models.SmallIntegerField(
                        choices=[(0, "发起"), (1, "通过"), (2, "拒绝"), (3, "撤销")],
                        default=0,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="", max_length=500, verbose_name="审批意见"),
                ),
                ("delete_time", models.BigIntegerField(
                    default=0, verbose_name="删除时间")),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "mimu_flow_record",
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="流程名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="流程代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="流程描述")),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("expense", "报销审批"),
                            ("leave", "请假审批"),
                            ("purchase", "采购审批"),
                            ("contract", "合同审批"),
                            ("other", "其他审批"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="流程类型",
                    ),
                ),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认流程"),
                ),
            ],
            options={
                "verbose_name": "审批流程",
                "verbose_name_plural": "审批流程",
                "db_table": "oa_approval_flow",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("approved", "同意"),
                            ("rejected", "拒绝"),
                            ("returned", "退回"),
                        ],
                        max_length=20,
                        verbose_name="审批结果",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "approval_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="审批时间"),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "oa_approval_record",
                "ordering": ["-approval_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="申请标题")),
                ("content", models.TextField(verbose_name="申请内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("in_review", "审核中"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已撤销"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "complete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"),
                ),
                ("attachments", models.TextField(blank=True, verbose_name="附件列表")),
            ],
            options={
                "verbose_name": "审批申请",
                "verbose_name_plural": "审批申请",
                "db_table": "oa_approval_request",
                "ordering": ["-submit_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("user", "指定用户"),
                            ("role", "指定角色"),
                            ("department_leader", "部门负责人"),
                            ("direct_supervisor", "直属上级"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="审批人类型",
                    ),
                ),
                ("is_required", models.BooleanField(
                    default=True, verbose_name="是否必须")),
                ("can_skip", models.BooleanField(
                    default=False, verbose_name="是否可跳过")),
                (
                    "timeout_hours",
                    models.IntegerField(default=24, verbose_name="超时时间(小时)"),
                ),
            ],
            options={
                "verbose_name": "审批步骤",
                "verbose_name_plural": "审批步骤",
                "db_table": "oa_approval_step",
                "ordering": ["flow", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="会议主题")),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("regular", "例会"),
                            ("project", "项目会议"),
                            ("training", "培训会议"),
                            ("review", "评审会议"),
                            ("emergency", "紧急会议"),
                            ("other", "其他"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="会议类型",
                    ),
                ),
                ("meeting_date", models.DateTimeField(verbose_name="会议开始时间")),
                ("meeting_end_time", models.DateTimeField(verbose_name="会议结束时间")),
                ("duration", models.IntegerField(
                    default=60, verbose_name="会议时长(分钟)")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="会议地点"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("confirmed", "已确认"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("postponed", "已延期"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="会议状态",
                    ),
                ),
                ("agenda", models.TextField(blank=True, verbose_name="会议议程")),
                ("content", models.TextField(blank=True, verbose_name="会议内容")),
                ("summary", models.TextField(blank=True, verbose_name="会议纪要摘要")),
                ("resolution", models.TextField(blank=True, verbose_name="会议决议")),
                ("action_items", models.TextField(blank=True, verbose_name="行动项")),
                (
                    "next_meeting",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次会议时间"),
                ),
                ("attachments", models.TextField(blank=True, verbose_name="会议附件")),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="meeting_recordings/",
                        verbose_name="会议录音",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                        null=True,
                        verbose_name="会议评分",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="会议反馈")),
            ],
            options={
                "verbose_name": "会议记录",
                "verbose_name_plural": "会议记录",
                "db_table": "oa_meeting_record",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRecordAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议记录实际出席人员",
                "verbose_name_plural": "会议记录实际出席人员",
                "db_table": "oa_meeting_record_attendees",
            },
        ),
        migrations.CreateModel(
            name="MeetingRecordParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议记录与会人员",
                "verbose_name_plural": "会议记录与会人员",
                "db_table": "oa_meeting_record_participants",
            },
        ),
        migrations.CreateModel(
            name="MeetingRecordSharedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议记录共享人员",
                "verbose_name_plural": "会议记录共享人员",
                "db_table": "oa_meeting_record_shared_users",
            },
        ),
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="会议室名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="会议室编号"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="会议室位置")),
                ("capacity", models.IntegerField(default=10, verbose_name="容纳人数")),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="是否有投影仪"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=False, verbose_name="是否有白板"),
                ),
                ("has_tv", models.BooleanField(default=False, verbose_name="是否有电视")),
                ("has_phone", models.BooleanField(
                    default=False, verbose_name="是否有电话")),
                ("has_wifi", models.BooleanField(
                    default=True, verbose_name="是否有WiFi")),
                ("equipment_list", models.TextField(
                    blank=True, verbose_name="设备清单")),
                ("description", models.TextField(blank=True, verbose_name="会议室描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("inactive", "禁用"),
                            ("pending", "待审核"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议室",
                "verbose_name_plural": "会议室",
                "db_table": "oa_meeting_room",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OAMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="消息标题")),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("system", "系统消息"),
                            ("notice", "通知消息"),
                            ("personal", "个人消息"),
                            ("group", "群组消息"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("user", "指定用户"),
                            ("department", "指定部门"),
                            ("role", "指定角色"),
                            ("all", "全体用户"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="接收类型",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                ("is_draft", models.BooleanField(
                    default=False, verbose_name="是否草稿")),
                (
                    "send_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"),
                ),
                ("attachments", models.TextField(blank=True, verbose_name="附件列表")),
            ],
            options={
                "verbose_name": "消息管理",
                "verbose_name_plural": "消息管理",
                "db_table": "oa_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="汇报工作ID"),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("labor_time", models.FloatField(default=0.0, verbose_name="工时")),
                ("admin_id", models.IntegerField(default=1, verbose_name="用户ID")),
                ("did", models.IntegerField(default=1, verbose_name="部门ID")),
                ("labor_type", models.IntegerField(
                    default=1, verbose_name="工作类型")),
                (
                    "cid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="工作分类ID"),
                ),
                (
                    "tid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="任务ID"),
                ),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                ("delete_time", models.BigIntegerField(
                    default=0, verbose_name="删除时间")),
                ("create_time", models.BigIntegerField(
                    default=0, verbose_name="创建时间")),
                ("update_time", models.BigIntegerField(
                    default=0, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "工作日程",
                "verbose_name_plural": "工作日程",
                "db_table": "oa_schedule",
            },
        ),
        migrations.CreateModel(
            name="OAMessageReadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="更新时间"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_records",
                        to="oa.oamessage",
                        verbose_name="消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息阅读记录",
                "verbose_name_plural": "消息阅读记录",
                "db_table": "oa_message_read_record",
            },
        ),
    ]
