# Generated by Django 5.2.5 on 2026-01-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oa', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='发布部门'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='received_announcements', to='user.department', verbose_name='目标部门'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='received_announcements', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='announcementreadrecord',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='oa.announcement', verbose_name='公告'),
        ),
        migrations.AddField(
            model_name='announcementreadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='阅读用户'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='departments',
            field=models.ManyToManyField(blank=True, to='user.department', verbose_name='适用部门'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='申请部门'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oa.approvalflow', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='oa.approvalrequest', verbose_name='审批申请'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approvers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='oa.approvalflow', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oa.approvalstep', verbose_name='当前步骤'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oa.approvalstep', verbose_name='审批步骤'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department', verbose_name='组织部门'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='主持人'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_meetings', to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='meetingrecordattendee',
            name='meetingrecord',
            field=models.ForeignKey(db_column='meetingrecord_id', on_delete=django.db.models.deletion.CASCADE, to='oa.meetingrecord'),
        ),
        migrations.AddField(
            model_name='meetingrecordattendee',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='signed_meetings', through='oa.MeetingRecordAttendee', to=settings.AUTH_USER_MODEL, verbose_name='实际出席人员'),
        ),
        migrations.AddField(
            model_name='meetingrecordparticipant',
            name='meetingrecord',
            field=models.ForeignKey(db_column='meetingrecord_id', on_delete=django.db.models.deletion.CASCADE, to='oa.meetingrecord'),
        ),
        migrations.AddField(
            model_name='meetingrecordparticipant',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_meetings', through='oa.MeetingRecordParticipant', to=settings.AUTH_USER_MODEL, verbose_name='参会人员'),
        ),
        migrations.AddField(
            model_name='meetingrecordshareduser',
            name='meetingrecord',
            field=models.ForeignKey(db_column='meetingrecord_id', on_delete=django.db.models.deletion.CASCADE, to='oa.meetingrecord'),
        ),
        migrations.AddField(
            model_name='meetingrecordshareduser',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_meetings', through='oa.MeetingRecordSharedUser', to=settings.AUTH_USER_MODEL, verbose_name='共享人员'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oa.meetingroom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='oa.message', verbose_name='父消息'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_departments',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to='user.department', verbose_name='接收部门'),
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
        migrations.AddField(
            model_name='messagereadrecord',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='oa.message', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='messagereadrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='阅读用户'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type'], name='idx_announce_type'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publisher'], name='idx_announce_publisher'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_date'], name='idx_announce_publish'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_published'], name='idx_announce_published'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_top'], name='idx_announce_top'),
        ),
        migrations.AddIndex(
            model_name='announcementreadrecord',
            index=models.Index(fields=['announcement'], name='idx_read_announce'),
        ),
        migrations.AddIndex(
            model_name='announcementreadrecord',
            index=models.Index(fields=['user'], name='idx_read_user'),
        ),
        migrations.AddIndex(
            model_name='announcementreadrecord',
            index=models.Index(fields=['read_time'], name='idx_read_time'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementreadrecord',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['code'], name='idx_flow_code'),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['flow_type'], name='idx_flow_type'),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['is_active'], name='idx_flow_active'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['flow'], name='idx_step_flow'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['step_order'], name='idx_step_order'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['applicant'], name='idx_approval_applicant'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['flow'], name='idx_approval_flow'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='idx_approval_status'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['submit_time'], name='idx_approval_submit'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['request'], name='idx_approval_rec_request'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['approver'], name='idx_approval_rec_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['result'], name='idx_approval_rec_result'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingrecordattendee',
            unique_together={('meetingrecord', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingrecordparticipant',
            unique_together={('meetingrecord', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingrecordshareduser',
            unique_together={('meetingrecord', 'user')},
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['code'], name='idx_room_code'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['status'], name='idx_room_status'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['meeting_date'], name='idx_meeting_date'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['host'], name='idx_meeting_host'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['department'], name='idx_meeting_dept'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['status'], name='idx_meeting_status'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['room'], name='idx_meeting_room'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='idx_msg_sender'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='idx_msg_type'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['send_time'], name='idx_msg_send_time'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_draft'], name='idx_msg_draft'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['priority'], name='idx_msg_priority'),
        ),
        migrations.AddIndex(
            model_name='messagereadrecord',
            index=models.Index(fields=['message'], name='idx_msg_read_message'),
        ),
        migrations.AddIndex(
            model_name='messagereadrecord',
            index=models.Index(fields=['user'], name='idx_msg_read_user'),
        ),
        migrations.AddIndex(
            model_name='messagereadrecord',
            index=models.Index(fields=['is_read'], name='idx_msg_read_status'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadrecord',
            unique_together={('message', 'user')},
        ),
    ]
