# Generated by Django 4.2.27 on 2026-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oa", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingrecord",
            name="ai_extracted_tasks",
            field=models.JSONField(blank=True, default=list, verbose_name="AI提取待办任务"),
        ),
        migrations.AddField(
            model_name="meetingrecord",
            name="ai_generated_summary",
            field=models.TextField(blank=True, null=True, verbose_name="AI自动提取摘要"),
        ),
        migrations.AddField(
            model_name="meetingrecord",
            name="ai_transcript",
            field=models.TextField(blank=True, null=True, verbose_name="录音转文本内容"),
        ),
    ]
