# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="审批标题"),
                ),
                (
                    "type_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="审批类型ID"),
                ),
                (
                    "applicant_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="申请人ID"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "待审批"),
                            (1, "审批中"),
                            (2, "已通过"),
                            (3, "已拒绝"),
                            (4, "已取消"),
                        ],
                        default=0,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="申请内容"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "current_step_order",
                    models.IntegerField(default=1, verbose_name="当前步骤"),
                ),
            ],
            options={
                "verbose_name": "审批表",
                "verbose_name_plural": "审批表",
                "db_table": "mimu_approval",
            },
        ),
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="流程名称")),
                (
                    "code",
                    models.CharField(
                        default="FLOW_001",
                        max_length=50,
                        unique=True,
                        verbose_name="流程代码",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="流程描述")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "initiator_departments",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="可发起流程的部门ID，多个用逗号分隔",
                        max_length=500,
                        verbose_name="发起部门",
                    ),
                ),
                (
                    "initiator_roles",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="可发起流程的角色ID，多个用逗号分隔",
                        max_length=500,
                        verbose_name="发起角色",
                    ),
                ),
                (
                    "initiator_users",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="可发起流程的用户ID，多个用逗号分隔",
                        max_length=500,
                        verbose_name="发起用户",
                    ),
                ),
                (
                    "form_fields",
                    models.TextField(
                        blank=True, default="[]", verbose_name="自定义表单字段"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "审批流程",
                "verbose_name_plural": "审批流程",
                "db_table": "basedata_approval_flow",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField(
                    default=1, verbose_name="步骤序号")),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交"),
                            ("approve", "通过"),
                            ("reject", "拒绝"),
                            ("cancel", "取消"),
                            ("delegate", "委托"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="处理时间"),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "mimu_approval_record",
                "ordering": ["create_time"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_name", models.CharField(max_length=100, verbose_name="步骤名称")),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("department_head", "部门负责人"),
                            ("specific_user", "指定用户"),
                            ("department", "指定部门"),
                            ("role", "指定角色"),
                            ("level", "指定级别"),
                            ("cc", "抄送"),
                            ("notification", "通知"),
                            ("custom", "自定义条件"),
                        ],
                        default="department_head",
                        max_length=20,
                        verbose_name="步骤类型",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("approve", "审批"),
                            ("review", "审阅"),
                            ("sign", "会签"),
                            ("notify", "通知"),
                        ],
                        default="approve",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="审批角色"),
                ),
                (
                    "approver_department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="审批部门"),
                ),
                (
                    "approver_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="审批级别"),
                ),
                (
                    "cc_users",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="多个用户ID用逗号分隔",
                        max_length=500,
                        verbose_name="抄送用户",
                    ),
                ),
                (
                    "notification_users",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="多个用户ID用逗号分隔",
                        max_length=500,
                        verbose_name="通知用户",
                    ),
                ),
                (
                    "cc_roles",
                    models.CharField(
                        blank=True,
                        help_text="多个角色用逗号分隔",
                        max_length=500,
                        verbose_name="抄送角色",
                    ),
                ),
                (
                    "cc_departments",
                    models.CharField(
                        blank=True,
                        help_text="多个部门用逗号分隔",
                        max_length=500,
                        verbose_name="抄送部门",
                    ),
                ),
                (
                    "condition_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="条件字段"),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        blank=True,
                        help_text="如：>, <, =, >=, <=, in, not_in",
                        max_length=20,
                        verbose_name="条件操作符",
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="条件值"),
                ),
                (
                    "time_limit_hours",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="处理时限(小时)"),
                ),
                (
                    "auto_approve_on_timeout",
                    models.BooleanField(default=False, verbose_name="超时自动通过"),
                ),
                ("description", models.TextField(blank=True, verbose_name="步骤说明")),
                ("is_required", models.BooleanField(
                    default=True, verbose_name="是否必须")),
                (
                    "is_parallel",
                    models.BooleanField(default=False, verbose_name="是否并行处理"),
                ),
                (
                    "allow_delegate",
                    models.BooleanField(default=True, verbose_name="允许委托"),
                ),
                ("allow_skip", models.BooleanField(
                    default=False, verbose_name="允许跳过")),
                (
                    "require_comment",
                    models.BooleanField(default=True, verbose_name="需要审批意见"),
                ),
                (
                    "comment_hint",
                    models.CharField(
                        default="请输入审批意见", max_length=200, verbose_name="意见提示文字"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "审批步骤",
                "verbose_name_plural": "审批步骤",
                "db_table": "basedata_approval_step",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类型名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="图标"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(
                    default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "审批类型",
                "verbose_name_plural": "审批类型",
                "db_table": "basedata_approval_type",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
