# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approval", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_steps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="approval.approvalflow",
                verbose_name="所属流程",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="approval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="approval.approval",
                verbose_name="审批",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_handled_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="approvalflow",
            name="approval_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="approval.approvaltype",
                verbose_name="审批类型",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="flow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="approval.approvalflow",
                verbose_name="审批流程",
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
    ]
