# Generated by Django 5.2.1 on 2026-01-07 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_add_reviewer_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='approval_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.approvaltype', verbose_name='审批类型'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='cc_users',
            field=models.CharField(blank=True, default='', help_text='多个用户ID用逗号分隔', max_length=500, verbose_name='抄送用户'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='notification_users',
            field=models.CharField(blank=True, default='', help_text='多个用户ID用逗号分隔', max_length=500, verbose_name='通知用户'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='step_type',
            field=models.CharField(choices=[('department_head', '部门负责人'), ('specific_user', '指定用户'), ('department', '指定部门'), ('role', '指定角色'), ('level', '指定级别'), ('cc', '抄送'), ('notification', '通知'), ('custom', '自定义条件')], default='department_head', max_length=20, verbose_name='步骤类型'),
        ),
    ]
