# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approvalflow_approval_type_approvalstep_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='initiator_departments',
            field=models.CharField(blank=True, default='', help_text='可发起流程的部门ID，多个用逗号分隔', max_length=500, verbose_name='发起部门'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='initiator_roles',
            field=models.CharField(blank=True, default='', help_text='可发起流程的角色ID，多个用逗号分隔', max_length=500, verbose_name='发起角色'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='initiator_users',
            field=models.CharField(blank=True, default='', help_text='可发起流程的用户ID，多个用逗号分隔', max_length=500, verbose_name='发起用户'),
        ),
    ]
