# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_approvalflow_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_applications', to='auth.user', verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='approval',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='申请内容'),
        ),
        migrations.AddField(
            model_name='approval',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval.approvalflow', verbose_name='审批流程'),
        ),
    ]
