# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='申请内容'),
        ),
    ]
