# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_remove_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='form_fields',
            field=models.TextField(blank=True, default='[]', verbose_name='自定义表单字段'),
        ),
    ]
