# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_approvalflow_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='comment_hint',
            field=models.CharField(default='请输入审批意见', max_length=200, verbose_name='意见提示文字'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='require_comment',
            field=models.BooleanField(default=True, verbose_name='需要审批意见'),
        ),
    ]
