# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_approvalstep_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='current_step_order',
            field=models.IntegerField(default=1, verbose_name='当前步骤'),
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(default=1, verbose_name='步骤序号')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '通过'), ('reject', '拒绝'), ('cancel', '取消'), ('delegate', '委托')], max_length=20, verbose_name='操作类型')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('handler_id', models.IntegerField(default=0, verbose_name='处理人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='approval.approval', verbose_name='审批')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_records', to='auth.user', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'ordering': ['create_time'],
                'db_table': 'mimu_approval_record',
            },
        ),
    ]
