# Generated by Django 4.2.27 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkCate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="分类名称"),
                ),
                ("pid", models.IntegerField(default=0, verbose_name="父级ID")),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("status", models.IntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "工作分类",
                "verbose_name_plural": "工作分类",
                "db_table": "work_cate",
            },
        ),
    ]
